// Define an array of songs with their paths and names

// listNum: 1: JW3  | 2: DRFL | 3: GB&GR | 4: 999 | 5: WRLD on Drugs | 6: JuiceTheKidd
const songlist = [
  { src: "songs/2019 My Year.mp3", name: "2019 My Year", listNum: 2 },
  { src: "songs/4 Instance.mp3", name: "4 Instance", listNum: 1 },
  { src: "songs/6.mp3", name: "6", listNum: 1 },
  { src: "songs/24 Hours.mp3", name: "24 Hours", listNum: 5 },
  { src: "songs/27 Club.mp3", name: "27 Club", listNum: 3 },
  { src: "songs/38 Special.mp3", name: ".38 Special", listNum: 1 },
  { src: "songs/70s.mp3", name: "'70s", listNum: 2 },
  { src: "songs/Adore You.mp3", name: "Adore You", listNum: 1 },
  {
    src: "songs/Airport Security.mp3",
    name: "Airport Security (feat. Lil Yachty)",
    listNum: 3,
  },
  { src: "songs/All Out.mp3", name: "All Out", listNum: 5 },
  { src: "songs/Anxiety.mp3", name: "Anxiety", listNum: 2 },
  { src: "songs/Back In Chicago.mp3", name: "Back In Chicago", listNum: 3 },
  {
    src: "songs/Barbarian (Vandal).mp3",
    name: "Barbarian (Vandal)",
    listNum: 1,
  },
  {
    src: "songs/Best Of 'Em (Western).mp3",
    name: "Best Of 'Em (Western)",
    listNum: 2,
  },
  { src: "songs/Big Dog.mp3", name: "Big Dog", listNum: 2 },
  {
    src: "songs/Billy Idol (Mary Jane).mp3",
    name: "Billy Idol (Mary Jane)",
    listNum: 3,
  },
  {
    src: "songs/Biscotti In The Air.mp3",
    name: "Biscotti In The Air",
    listNum: 1,
  },
  { src: "songs/Both Ways.mp3", name: "Both Ways", listNum: 1 },
  { src: "songs/Bottle.mp3", name: "Bottle", listNum: 3 },
  {
    src: "songs/Bullet For My Valentine.mp3",
    name: "Bullet For My Valentine",
    listNum: 1,
  },
  { src: "songs/Busch.mp3", name: "Busch", listNum: 5 },
  { src: "songs/Cake.mp3", name: "Cake", listNum: 5 },
  { src: "songs/Californication.mp3", name: "Californication", listNum: 1 },
  { src: "songs/Chimp.mp3", name: "Chimp", listNum: 3 },
  { src: "songs/Codeine Cobain.mp3", name: "Codeine Cobain", listNum: 2 },
  {
    src: "songs/Common Sense (Worth It).mp3",
    name: "Common Sense (Worth It)",
    listNum: 5,
  },
  { src: "songs/Condone It.mp3", name: "Condone It", listNum: 2 },
  {
    src: "songs/Contained (Change).mp3",
    name: "Contained (Change)",
    listNum: 2,
  },
  { src: "songs/Coraline.mp3", name: "Coraline", listNum: 1 },
  { src: "songs/Cursed.mp3", name: "Cursed", listNum: 2 },
  {
    src: "songs/Dark Thoughts (On Your Mind).mp3",
    name: "Dark Thoughts (On Your Mind)",
    listNum: 1,
  },
  { src: "songs/Day One (v2).mp3", name: "Day One (v2)", listNum: 1 },
  {
    src: "songs/Death Penalty (Dark Queen).mp3",
    name: "Death Penalty (Dark Queen)",
    listNum: 3,
  },
  { src: "songs/Deprived.mp3", name: "Deprived", listNum: 3 },
  {
    src: "songs/Do The Most (No Coaster).mp3",
    name: "Do The Most (No Coaster)",
    listNum: 2,
  },
  { src: "songs/Don't Forget Me.mp3", name: "Don't Forget Me", listNum: 1 },
  { src: "songs/Draco On Me.mp3", name: "Draco On Me", listNum: 2 },
  {
    src: "songs/Drugs Are My Friends.mp3",
    name: "Drugs Are My Friends",
    listNum: 1,
  },
  { src: "songs/Dummy.mp3", name: "Dummy", listNum: 3 },
  {
    src: "songs/Fast Forward (Passport).mp3",
    name: "Fast Forward (Passport)",
    listNum: 5,
  },
  { src: "songs/Fenty (Let It Go).mp3", name: "Fenty (Let It Go)", listNum: 3 },
  { src: "songs/Flight To London.mp3", name: "Flight To London", listNum: 1 },
  { src: "songs/Floor It.mp3", name: "Floor It", listNum: 1 },
  {
    src: "songs/For The Team (feat. Lil Yachty).mp3",
    name: "For The Team (feat. Lil Yachty)",
    listNum: 1,
  },
  { src: "songs/Four Words.mp3", name: "Four Words", listNum: 5 },
  { src: "songs/Friends Die.mp3", name: "Friends Die", listNum: 5 },
  { src: "songs/From Afar.mp3", name: "From Afar", listNum: 2 },
  {
    src: "songs/Girl With The Blonde Hair.mp3",
    name: "Girl With The Blonde Hair",
    listNum: 5,
  },
  { src: "songs/Give Me My Fix.mp3", name: "Give Me My Fix", listNum: 2 },
  {
    src: "songs/Good Times (feat. Kid Cudi).mp3",
    name: "Good Times (feat. Kid Cudi)",
    listNum: 1,
  },
  { src: "songs/GoPro.mp3", name: "GoPro", listNum: 1 },
  { src: "songs/Goyard Bag.mp3", name: "Goyard Bag", listNum: 2 },
  { src: "songs/Grace.mp3", name: "Grace", listNum: 3 },
  { src: "songs/GTA.mp3", name: "GTA", listNum: 5 },
  { src: "songs/Gucci Purse.mp3", name: "Gucci Purse", listNum: 3 },
  { src: "songs/Hypnotic.mp3", name: "Hypnotic", listNum: 3 },
  { src: "songs/I Want It (v1).mp3", name: "I Want It (v1)", listNum: 1 },
  {
    src: "songs/I Wonder (My Mind).mp3",
    name: "I Wonder (My Mind)",
    listNum: 5,
  },
  { src: "songs/In The Air.mp3", name: "In The Air", listNum: 5 },
  {
    src: "songs/Inner Peace (Travelling).mp3",
    name: "Inner Peace (Travelling)",
    listNum: 5,
  },
  {
    src: "songs/Irony (Inspire Me).mp3",
    name: "Irony (Inspire Me)",
    listNum: 2,
  },
  { src: "songs/Irony.mp3", name: "Irony", listNum: 3 },
  { src: "songs/Jeffery.mp3", name: "Jeffery", listNum: 3 },
  { src: "songs/Karate Kid.mp3", name: "Karate Kid", listNum: 1 },
  { src: "songs/Keep It.mp3", name: "Keep It", listNum: 1 },
  { src: "songs/Kickflip.mp3", name: "Kickflip", listNum: 3 },
  { src: "songs/KTM Drip.mp3", name: "KTM Drip", listNum: 1 },
  {
    src: "songs/Let Me Be (Lone Ranger).mp3",
    name: "Let Me Be (Lone Ranger)",
    listNum: 1,
  },
  { src: "songs/Life's A Dungeon.mp3", name: "Life's A Dungeon", listNum: 1 },
  {
    src: "songs/Lock On (Dark Arts).mp3",
    name: "Lock On (Dark Arts)",
    listNum: 1,
  },
  { src: "songs/Lonely.mp3", name: "Lonely", listNum: 1 },
  { src: "songs/Long Time Coming.mp3", name: "Long Time Coming", listNum: 1 },
  { src: "songs/Love Cage.mp3", name: "Love Cage", listNum: 3 },
  { src: "songs/Love Over There.mp3", name: "Love Over There", listNum: 1 },
  { src: "songs/Love Story.mp3", name: "Love Story", listNum: 1 },
  { src: "songs/Luigi (Twins).mp3", name: "Luigi (Twins)", listNum: 5 },
  { src: "songs/Made It Work.mp3", name: "Made It Work", listNum: 1 },
  {
    src: "songs/Man Down (Rockstar Boy).mp3",
    name: "Man Down (Rockstar Boy)",
    listNum: 1,
  },
  { src: "songs/Mansion.mp3", name: "Mansion", listNum: 2 },
  { src: "songs/Maybe (Master).mp3", name: "Maybe (Master)", listNum: 1 },
  {
    src: "songs/McLaren Drive (Tic-Tac-Toe).mp3",
    name: "McLaren Drive (Tic-Tac-Toe)",
    listNum: 2,
  },
  { src: "songs/Meadows (Mix).mp3", name: "Meadows (Mix)", listNum: 3 },
  { src: "songs/Minus.mp3", name: "Minus", listNum: 5 },
  { src: "songs/Money Over Hoes.mp3", name: "Money Over Hoes", listNum: 1 },
  { src: "songs/Morphine.mp3", name: "Morphine", listNum: 5 },
  { src: "songs/My Year.mp3", name: "My Year", listNum: 1 },
  { src: "songs/Naruto.mp3", name: "Naruto", listNum: 3 },
  { src: "songs/Nesquick.mp3", name: "Nesquick", listNum: 3 },
  { src: "songs/No Depot (Nemo).mp3", name: "No Depot (Nemo)", listNum: 3 },
  { src: "songs/No Reason.mp3", name: "No Reason", listNum: 1 },
  { src: "songs/No Wrong.mp3", name: "No Wrong", listNum: 1 },
  {
    src: "songs/Nobody (feat. Lil Yachty).mp3",
    name: "Nobody (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/Not Sorry.mp3", name: "Not Sorry", listNum: 3 },
  { src: "songs/Numb The Pain.mp3", name: "Numb The Pain", listNum: 3 },
  { src: "songs/OJ Glove.mp3", name: "OJ Glove", listNum: 1 },
  { src: "songs/Omen.mp3", name: "Omen", listNum: 1 },
  { src: "songs/On The Regular.mp3", name: "On The Regular", listNum: 5 },
  { src: "songs/On The Road.mp3", name: "On The Road", listNum: 1 },
  {
    src: "songs/Only You On My Mind.mp3",
    name: "Only You On My Mind",
    listNum: 1,
  },
  { src: "songs/Percaholic.mp3", name: "Percaholic", listNum: 3 },
  { src: "songs/Potions.mp3", name: "Potions", listNum: 3 },
  { src: "songs/Purple Moncler.mp3", name: "Purple Moncler", listNum: 2 },
  { src: "songs/Quitter.mp3", name: "Quitter", listNum: 3 },
  { src: "songs/Racks In.mp3", name: "Racks In", listNum: 5 },
  { src: "songs/Rain Dance.mp3", name: "Rain Dance", listNum: 1 },
  { src: "songs/Reason.mp3", name: "Reason", listNum: 1 },
  {
    src: "songs/Red Dead Redemption.mp3",
    name: "Red Dead Redemption",
    listNum: 2,
  },
  { src: "songs/Red Moonlight.mp3", name: "Red Moonlight", listNum: 1 },
  {
    src: "songs/Remind Me Of The Summer.mp3",
    name: "Remind Me Of The Summer",
    listNum: 3,
  },
  {
    src: "songs/Rental (Cha-Ching).mp3",
    name: "Rental (Cha-Ching)",
    listNum: 2,
  },
  { src: "songs/Same Clothes.mp3", name: "Same Clothes", listNum: 3 },
  { src: "songs/Sexual Healing.mp3", name: "Sexual Healing", listNum: 2 },
  { src: "songs/Shadows.mp3", name: "Shadows", listNum: 1 },
  { src: "songs/Singalong.mp3", name: "Singalong", listNum: 2 },
  { src: "songs/Sippin Red.mp3", name: "Sippin Red", listNum: 1 },
  { src: "songs/Sky High.mp3", name: "Sky High", listNum: 5 },
  { src: "songs/Slasher.mp3", name: "Slasher", listNum: 3 },
  { src: "songs/Sleep Paralysis.mp3", name: "Sleep Paralysis", listNum: 3 },
  { src: "songs/Slow Me Down.mp3", name: "Slow Me Down", listNum: 1 },
  { src: "songs/So Fast.mp3", name: "Drivin' So Fast", listNum: 2 },
  {
    src: "songs/Soda Pop (feat. Roddy Ricch).mp3",
    name: "Soda Pop (feat. Roddy Ricch)",
    listNum: 1,
  },
  { src: "songs/Spanglish.mp3", name: "Spanglish", listNum: 5 },
  {
    src: "songs/Split My Brain (808 Freestyle).mp3",
    name: "Split My Brain (808 Freestyle)",
    listNum: 1,
  },
  {
    src: "songs/Stabbed You (Had To).mp3",
    name: "Stabbed You (Had To)",
    listNum: 5,
  },
  {
    src: "songs/Stargazing (Not An Option).mp3",
    name: "Stargazing (Not An Option)",
    listNum: 2,
  },
  { src: "songs/Starstruck (v3).mp3", name: "Starstruck (v3)", listNum: 5 },
  {
    src: "songs/Stick Talk (Lavagirl).mp3",
    name: "Stick Talk (Lavagirl)",
    listNum: 2,
  },
  { src: "songs/Stranger.mp3", name: "Stranger", listNum: 3 },
  {
    src: "songs/Tales Of The Toxic.mp3",
    name: "Tales Of The Toxic",
    listNum: 3,
  },
  { src: "songs/Talk Too Much(Master).mp3", name: "Talk Too Much", listNum: 1 },
  { src: "songs/Through My Head.mp3", name: "Through My Head", listNum: 2 },
  {
    src: "songs/To The Grave (Feelings).mp3",
    name: "To The Grave (Feelings)",
    listNum: 1,
  },
  { src: "songs/Triple 9 (999).mp3", name: "Triple 9 (999)", listNum: 4 },
  { src: "songs/Try Me.mp3", name: "Try Me", listNum: 5 },
  { src: "songs/Under Her Skin.mp3", name: "Under Her Skin", listNum: 2 },
  {
    src: "songs/Unexplainable.mp3",
    name: "Unexplainable (feat. The Kid LAROI)",
    listNum: 1,
  },
  { src: "songs/Victorious.mp3", name: "Victorious", listNum: 2 },
  { src: "songs/What Else.mp3", name: "What Else", listNum: 5 },
  { src: "songs/Whip (Alaska).mp3", name: "Whip (Alaska)", listNum: 5 },
  {
    src: "songs/Withdrawals.mp3",
    name: "Withdrawals (High Again)",
    listNum: 5,
  },
  { src: "songs/X-Mas List.mp3", name: "X-Mas List", listNum: 1 },
  { src: "songs/Z Nation.mp3", name: "Z Nation", listNum: 5 },

  {
    src: "songs/All Alone (On My Own).mp3",
    name: "All Alone (On My Own)",
    listNum: 2,
  },
  { src: "songs/Alright.mp3", name: "Alright", listNum: 2 },
  {
    src: "songs/Always Workin' (Daily) (v2).mp3",
    name: "Always Workin' (Daily) (v2)",
    listNum: 2,
  },
  { src: "songs/Analog.mp3", name: "Analog", listNum: 3 },
  { src: "songs/Animal (v2).mp3", name: "Animal (v2)", listNum: 5 },
  { src: "songs/Attachments.mp3", name: "Attachments", listNum: 2 },
  { src: "songs/Bad Day.mp3", name: "Bad Day", listNum: 2 },
  { src: "songs/Bentley Truck.mp3", name: "Bentley Truck", listNum: 3 },
  { src: "songs/Beretta.mp3", name: "Beretta", listNum: 2 },
  {
    src: "songs/Best Around (Racks Out).mp3",
    name: "Best Around (Racks Out)",
    listNum: 2,
  },
  { src: "songs/Big Swag (v2).mp3", name: "Big Swag (v2)", listNum: 2 },
  {
    src: "songs/Bitch You're Done (v2).mp3",
    name: "Bitch You're Done (v2)",
    listNum: 5,
  },
  {
    src: "songs/Bitty (feat. Trippie Redd).mp3",
    name: "Bitty (feat. Trippie Redd)",
    listNum: 1,
  },
  { src: "songs/Bonjour (On Tour).mp3", name: "Bonjour (On Tour)", listNum: 2 },
  { src: "songs/Boondocks.mp3", name: "Boondocks", listNum: 5 },
  { src: "songs/Boss Of Me.mp3", name: "Boss Of Me", listNum: 2 },
  { src: "songs/Boy Wit Da Bandz.mp3", name: "Boy Wit Da Bandz", listNum: 3 },
  { src: "songs/Bussin.mp3", name: "Bussin", listNum: 5 },
  {
    src: "songs/Bye Bye Baby (feat. Young Thug).mp3",
    name: "Bye Bye Baby (feat. Young Thug)",
    listNum: 2,
  },
  { src: "songs/Carry It.mp3", name: "Carry It", listNum: 2 },
  { src: "songs/Chrome.mp3", name: "Chrome", listNum: 1 },
  { src: "songs/Codeine Casket.mp3", name: "Codeine Casket", listNum: 3 },

  { src: "songs/Cursed Heart.mp3", name: "Cursed Heart", listNum: 1 },
  { src: "songs/Dome.mp3", name: "Dome", listNum: 2 },
  { src: "songs/Don't Go + Widow.mp3", name: "Don't Go + Widow", listNum: 5 },
  { src: "songs/Dont Touch My Raf.mp3", name: "Dont Touch My Raf", listNum: 2 },
  {
    src: "songs/Door (feat. Chance The Rapper & Ant Clemons).mp3",
    name: "Door (feat. Chance The Rapper)",
    listNum: 2,
  },
  { src: "songs/Ducks.mp3", name: "Ducks", listNum: 2 },
  { src: "songs/Everlasting Love.mp3", name: "Everlasting Love", listNum: 3 },
  { src: "songs/Eyes Closed.mp3", name: "Eyes Closed", listNum: 2 },
  { src: "songs/Eyes Up.mp3", name: "Eyes Up", listNum: 2 },
  { src: "songs/Fire In My Lungs.mp3", name: "Fire In My Lungs", listNum: 1 },
  { src: "songs/Flaws.mp3", name: "Flaws", listNum: 3 },
  {
    src: "songs/Foo Foo (feat. G Herbo).mp3",
    name: "Foo Foo (feat. G Herbo)",
    listNum: 2,
  },
  { src: "songs/Forever Love.mp3", name: "Forever Love", listNum: 2 },
  { src: "songs/Fuck You Mean.mp3", name: "Fuck You Mean", listNum: 2 },
  { src: "songs/Get Geeked.mp3", name: "Get Geeked", listNum: 2 },
  { src: "songs/Girlfriend.mp3", name: "Girlfriend", listNum: 3 },
  { src: "songs/Glock Handler.mp3", name: "Glock Handler", listNum: 2 },
  { src: "songs/Good Day.mp3", name: "Good Day", listNum: 2 },
  { src: "songs/Haha.mp3", name: "Haha", listNum: 5 },
  { src: "songs/Hard To Digest.mp3", name: "Hard To Digest", listNum: 2 },
  { src: "songs/Heroine Music.mp3", name: "Heroine Music", listNum: 2 },
  { src: "songs/Hit A Lick.mp3", name: "Hit A Lick", listNum: 2 },
  { src: "songs/Home.mp3", name: "Home", listNum: 2 },
  { src: "songs/Hunnid.mp3", name: "Hunnid", listNum: 3 },
  { src: "songs/I Wonder.mp3", name: "I Wonder", listNum: 2 },
  { src: "songs/Iron On Me.mp3", name: "Iron On Me", listNum: 2 },
  { src: "songs/Jack & Jill.mp3", name: "Jack & Jill", listNum: 2 },
  { src: "songs/Juicy.mp3", name: "Juicy", listNum: 3 },
  { src: "songs/Junkie.mp3", name: "Junkie", listNum: 3 },
  { src: "songs/Kiki (King Kong).mp3", name: "Kiki (King Kong)", listNum: 5 },
  { src: "songs/Kirby's Selecta.mp3", name: "Kirby's Selecta", listNum: 3 },
  { src: "songs/Kurtis Blow.mp3", name: "Kurtis Blow", listNum: 2 },
  {
    src: "songs/Late Night Thoughts.mp3",
    name: "Late Night Thoughts",
    listNum: 2,
  },
  { src: "songs/Lavish.mp3", name: "Lavish", listNum: 3 },
  { src: "songs/Lean Wit Me (v2).mp3", name: "Lean Wit Me (v2)", listNum: 2 },
  { src: "songs/Left 4 Dead.mp3", name: "Left 4 Dead", listNum: 3 },
  { src: "songs/Let's Go.mp3", name: "Let's Go", listNum: 2 },
  { src: "songs/Live Forever.mp3", name: "Live Forever", listNum: 2 },
  {
    src: "songs/Living At The Top (Simple).mp3",
    name: "Living At The Top (Simple)",
    listNum: 2,
  },
  { src: "songs/London Tipton.mp3", name: "London Tipton", listNum: 3 },
  {
    src: "songs/Lost Too Many (Goblin).mp3",
    name: "Lost Too Many (Goblin)",
    listNum: 2,
  },
  { src: "songs/Love No Hoe.mp3", name: "Love No Hoe", listNum: 4 },
  { src: "songs/Lullabies.mp3", name: "Lullabies", listNum: 2 },
  { src: "songs/Lurkin (Sessions).mp3", name: "Lurkin (Sessions)", listNum: 2 },
  { src: "songs/Make It Sell.mp3", name: "Make It Sell", listNum: 4 },
  { src: "songs/Maserati.mp3", name: "Maserati", listNum: 2 },
  { src: "songs/Meadows.mp3", name: "Meadows", listNum: 3 },
  { src: "songs/Mind Games.mp3", name: "Mind Games", listNum: 4 },
  {
    src: "songs/Misery Avenue (v3).mp3",
    name: "Misery Avenue (v3)",
    listNum: 2,
  },
  { src: "songs/Molly & Mike.mp3", name: "Molly & Mike", listNum: 3 },
  { src: "songs/Moncler Year.mp3", name: "Moncler Year", listNum: 2 },
  {
    src: "songs/Mr. Heartbreak (v3).mp3",
    name: "Mr. Heartbreak (v3)",
    listNum: 3,
  },
  {
    src: "songs/My Gang (Together).mp3",
    name: "My Gang (Together)",
    listNum: 2,
  },
  {
    src: "songs/My Phone (Sessions).mp3",
    name: "My Phone (Sessions)",
    listNum: 3,
  },
  { src: "songs/Narcotics.mp3", name: "Narcotics", listNum: 5 },
  {
    src: "songs/Nascar (feat. 147 Calboy).mp3",
    name: "Nascar (feat. 147 Calboy)",
    listNum: 3,
  },
  { src: "songs/Never Cared.mp3", name: "Never Cared", listNum: 5 },
  { src: "songs/No Benefits.mp3", name: "No Benefits", listNum: 3 },
  { src: "songs/No Fears.mp3", name: "No Fears", listNum: 2 },
  { src: "songs/No Laces.mp3", name: "No Laces", listNum: 2 },
  { src: "songs/No More.mp3", name: "No More", listNum: 2 },
  { src: "songs/No Trespassing.mp3", name: "No Trespassing", listNum: 2 },
  {
    src: "songs/Nobody (Blue Shit).mp3",
    name: "Nobody (Blue Shit)",
    listNum: 2,
  },
  { src: "songs/Not Ashamed.mp3", name: "Not Ashamed", listNum: 2 },
  { src: "songs/On Time.mp3", name: "On Time", listNum: 1 },
  { src: "songs/Orange.mp3", name: "Orange", listNum: 2 },
  { src: "songs/Oversprung.mp3", name: "Over Sprung", listNum: 1 },
  { src: "songs/Pain Feels.mp3", name: "Pain Feels", listNum: 2 },
  { src: "songs/Pause.mp3", name: "Pause", listNum: 5 },
  { src: "songs/Perc Floating.mp3", name: "Perc Floating", listNum: 3 },
  { src: "songs/Plug.mp3", name: "Plug", listNum: 3 },
  { src: "songs/Pop Rock.mp3", name: "Pop Rock", listNum: 5 },
  {
    src: "songs/Psychedelic (Feeling Myself).mp3",
    name: "Psychedelic (Feeling Myself)",
    listNum: 3,
  },
  { src: "songs/Purple Substance.mp3", name: "Purple Substance", listNum: 1 },
  { src: "songs/Python.mp3", name: "Python", listNum: 3 },
  { src: "songs/Rich Forever.mp3", name: "Rich Forever", listNum: 1 },
  { src: "songs/Right Or Wrong.mp3", name: "Right Or Wrong", listNum: 3 },
  { src: "songs/Rugrats.mp3", name: "Rugrats", listNum: 2 },
  { src: "songs/Run That Shit.mp3", name: "Run That Shit", listNum: 2 },
  { src: "songs/Scars.mp3", name: "Scars", listNum: 3 },
  {
    src: "songs/Show Me Love (27 Club).mp3",
    name: "Show Me Love (27 Club)",
    listNum: 3,
  },
  { src: "songs/Slenderman.mp3", name: "Slenderman", listNum: 3 },
  { src: "songs/Slide.mp3", name: "Slide", listNum: 5 },
  { src: "songs/So What.mp3", name: "So What", listNum: 5 },
  {
    src: "songs/Stumblin' (feat. Lil Yachty).mp3",
    name: "Stumblin' (feat. Lil Yachty)",
    listNum: 2,
  },
  { src: "songs/Sugarfish.mp3", name: "Sugarfish", listNum: 3 },
  { src: "songs/Swear.mp3", name: "Swear", listNum: 1 },
  {
    src: "songs/Swisher (Hilfiger).mp3",
    name: "Swisher (Hilfiger)",
    listNum: 3,
  },
  { src: "songs/Tag.mp3", name: "Tag", listNum: 5 },
  {
    src: "songs/Take Off (Sessions).mp3",
    name: "Take Off (Sessions)",
    listNum: 5,
  },
  {
    src: "songs/Takeover (feat. Lil Yachty).mp3",
    name: "Takever (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/Tattoos And Ink.mp3", name: "Tattoos And Ink", listNum: 1 },
  { src: "songs/Thrills.mp3", name: "Thrills", listNum: 5 },
  {
    src: "songs/Tonight (feat. Valee).mp3",
    name: "Tonight (feat. Valee)",
    listNum: 3,
  },
  {
    src: "songs/Trap Phone (feat. G Herbo).mp3",
    name: "Trap Phone (feat. G Herbo)",
    listNum: 3,
  },
  { src: "songs/Trees.mp3", name: "Trees", listnum: 3 },
  { src: "songs/Trick Or Treat.mp3", name: "Trick Or Treat", listNum: 3 },
  { src: "songs/Used And Abused.mp3", name: "Used And Abused", listNum: 2 },
  { src: "songs/VLone Thugs.mp3", name: "VLone Thugs", listNum: 2 },
  { src: "songs/Waves.mp3", name: "Waves", listNum: 2 },
  { src: "songs/Wavy.mp3", name: "Wavy", listNum: 3 },
  {
    src: "songs/Morning Again (Remaster).mp3",
    name: "Morning Again (Remaster)",
    listNum: 2,
  },
  {
    src: "songs/Toxic Humans (Remaster).mp3",
    name: "Toxic Humans (Remaster)",
    listNum: 2,
  },
  { src: "songs/Aquafina.mp3", name: "Aquafina (Remaster)", listNum: 2 },
  {
    src: "songs/Drive Me Crazy (Remaster).mp3",
    name: "Drive Me Crazy (Remaster)",
    listNum: 2,
  },
];

// Export the songs array for use in other scripts
export default songlist;
