// Define an array of songs with their paths and names

// listNum: 1: JW3  | 2: DRFL | 3: GB&GR | 4: 999 | 5: WRLD on Drugs | 6: Unsure | 7: Exclusives/Soundcloud | 8: JTK | 9: New | 0: Album title | 10: FIRST Album title
const songlist = [
  //#region NEW
  //{ src: "", name: "NEW PICKS", listNum: 10 }, // Title Button

  //#endregion

  { src: "", name: "WOD", listNum: 10 }, // Title Button
  //#region WOD
  // New Songs
  { src: "songs/For Fun.mp3", name: "For Fun", listNum: 5 },
  { src: "songs/Island.mp3", name: "Island", listNum: 5 },
  { src: "songs/Lemon Glow.mp3", name: "Lemon Glow", listNum: 5 },
  { src: "songs/Like a Riff.mp3", name: "Like a Riff", listNum: 5 },
  {
    src: "songs/Livin Life.mp3",
    name: "Livin Life (ft. Lil Yachty)",
    listNum: 5,
  },
  {
    src: "songs/Lobster Pizza.mp3",
    name: "Lobster Pizza (Chainsmokers)",
    listNum: 5,
  },
  { src: "songs/24 Hours.mp3", name: "24 Hours", listNum: 5 },
  {
    src: "songs/8 Minute Freestyle.mp3",
    name: "8 Minute Freestyle",
    listNum: 5,
  },
  { src: "songs/Abyss.mp3", name: "Abyss", listNum: 5 },
  { src: "songs/Abyss (Interlude).mp3", name: "Abyss (Interlude)", listNum: 5 },
  { src: "songs/All Out.mp3", name: "All Out", listNum: 5 },
  { src: "songs/All Smoke.mp3", name: "All Smoke", listNum: 5 },
  { src: "songs/Alright.mp3", name: "Alright", listNum: 5 },
  { src: "songs/Animal (v2).mp3", name: "Animal (v2)", listNum: 5 },
  {
    src: "songs/Always Workin' (Daily) (v2).mp3",
    name: "Always Workin' (v2)",
    listNum: 5,
  },
  { src: "songs/Another Way.mp3", name: "Another Way", listNum: 5 },
  {
    src: "songs/Anything But Normal.mp3",
    name: "Anything But Normal",
    listNum: 5,
  },
  { src: "songs/Army Armory.mp3", name: "Army Armory", listNum: 5 },
  { src: "songs/Back On It (Sessions).mp3", name: "Back On It", listNum: 5 },
  { src: "songs/Bad Day.mp3", name: "Bad Day", listNum: 5 },
  {
    src: "songs/Bad News (In My Arm).mp3",
    name: "Bad News (In My Arm)",
    listNum: 5,
  },

  {
    src: "songs/Bad To The Bone (Watch Yo Tone).mp3",
    name: "Bad To The Bone",
    listNum: 5,
  },

  { src: "songs/Ball.mp3", name: "Ball", listNum: 5 },
  { src: "songs/Battle Scars.mp3", name: "Battle Scars", listNum: 5 },
  { src: "songs/Beretta.mp3", name: "Beretta", listNum: 5 },
  { src: "songs/Big Swag (v2).mp3", name: "Big Swag (v2)", listNum: 5 },
  { src: "songs/Bird's Eye View.mp3", name: "Bird's Eye View", listNum: 5 },
  {
    src: "songs/Bitch You're Done (v2).mp3",
    name: "Bitch You're Done (v2)",
    listNum: 5,
  },
  {
    src: "songs/BITTER ASFF (feat. Juice WRLD).mp3",
    name: "BITTER ASFF (feat. KILL.ZERO)",
    listNum: 5,
  },
  {
    src: "songs/Blue Cash (feat. Juice WRLD).mp3",
    name: "Blue Cash (feat. Young Thug)",
    listNum: 5,
  },
  {
    src: "songs/Nobody (Blue Shit).mp3",
    name: "Blue Shit (Nobody)",
    listNum: 5,
  },
  { src: "songs/Blow Ya Brains v2.mp3", name: "Blow Ya Brains", listNum: 5 },
  { src: "songs/Body Bag.mp3", name: "Body Bag", listNum: 5 },
  {
    src: "songs/Boomerang (feat. Lil Yachty).mp3",
    name: "Boomerang (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/Boondocks.mp3", name: "Boondocks", listNum: 5 },
  { src: "songs/Both Ways.mp3", name: "Both Ways", listNum: 5 },
  { src: "songs/Buried Alive.mp3", name: "Buried Alive", listNum: 5 },
  { src: "songs/Busch.mp3", name: "Busch", listNum: 5 },
  { src: "songs/Bussin.mp3", name: "Bussin", listNum: 5 },
  { src: "songs/Cake.mp3", name: "Cake", listNum: 5 },
  {
    src: "songs/Can't Let Go (Sessions).mp3",
    name: "Can't Let Go",
    listNum: 5,
  },
  {
    src: "songs/Cash Up (Can't Keep Up).mp3",
    name: "Cash Up (Can't Keep Up)",
    listNum: 5,
  },
  { src: "songs/Cheat Code (No reload).mp3", name: "Cheat Code", listNum: 5 },
  {
    src: "songs/Common Sense (Worth It).mp3",
    name: "Common Sense (Worth It)",
    listNum: 5,
  },
  {
    src: "songs/Cooking Orders (Gun In The Bag).mp3",
    name: "Cooking Orders",
    listNum: 5,
  },
  {
    src: "songs/Couple M's (Chicago To LA).mp3",
    name: "Couple M's",
    listNum: 5,
  },
  {
    src: "songs/Different Dimensions.mp3",
    name: "Different Dimensions",
    listNum: 5,
  },
  {
    src: "songs/Do Re Mi (Man Down) (feat. G Herbo).mp3",
    name: "Do Re Mi (feat. G Herbo)",
    listNum: 5,
  },
  {
    src: "songs/Dont Touch My Raf.mp3",
    name: "Dont Touch My Raf",
    listNum: 5,
  },
  { src: "songs/Don't Go + Widow.mp3", name: "Don't Go + Widow", listNum: 5 },
  { src: "songs/Fall In Love.mp3", name: "Fall In Love", listNum: 5 },
  {
    src: "songs/Fast Forward (Passport).mp3",
    name: "Fast Forward (Passport)",
    listNum: 5,
  },
  {
    src: "songs/Feel Like A God (Rich & Dangerous) (Sessions).mp3",
    name: "Feel Like A God",
    listNum: 5,
  },
  {
    src: "songs/Flossin' (Zero Toleration).mp3",
    name: "Flossin' (Zero Toleration)",
    listNum: 5,
  },
  {
    src: "songs/For The Weekend (Facetious) (feat. G Herbo).mp3",
    name: "Facetious (feat. G Herbo)",
    listNum: 5,
  },
  {
    src: "songs/Foo Foo (feat. G Herbo).mp3",
    name: "Foo Foo (feat. G Herbo)",
    listNum: 5,
  },
  {
    src: "songs/For The Team (feat. Lil Yachty).mp3",
    name: "For The Team (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/For Your Life.mp3", name: "For Your Life", listNum: 5 },
  { src: "songs/Four Words.mp3", name: "Four Words", listNum: 5 },
  { src: "songs/Freaked It.mp3", name: "Freaked It", listNum: 5 },
  { src: "songs/Friends Die.mp3", name: "Friends Die", listNum: 5 },
  {
    src: "songs/Fuck You Mean.mp3",
    name: "Fuck You Mean (Feat. Trippie Redd)",
    listNum: 5,
  },
  {
    src: "songs/Gave Her All Of Me.mp3",
    name: "Gave Her All Of Me",
    listNum: 5,
  },
  {
    src: "songs/Girl With The Blonde Hair.mp3",
    name: "Girl With The Blonde Hair",
    listNum: 5,
  },
  { src: "songs/Globetrotter (Money).mp3", name: "Globetrotter", listNum: 5 },
  { src: "songs/Good Day.mp3", name: "Good Day", listNum: 5 },
  { src: "songs/Good Days.mp3", name: "Good Days", listNum: 5 },
  { src: "songs/Got Nothing On Me.mp3", name: "Got Nothing On Me", listNum: 5 },
  { src: "songs/Grateful (v1).mp3", name: "Grateful (v1)", listNum: 5 },
  { src: "songs/GTA.mp3", name: "GTA", listNum: 5 },
  {
    src: "songs/Gun You Down (2 Percs).mp3",
    name: "Gun You Down (2 Percs)",
    listNum: 5,
  },
  { src: "songs/Haha.mp3", name: "Haha", listNum: 5 },
  {
    src: "songs/Hellgirl (Sessions).mp3",
    name: "Hellgirl (Sessions)",
    listNum: 5,
  },
  { src: "songs/Her Friend.mp3", name: "Her Friend", listNum: 5 },
  { src: "songs/Hey Mister.mp3", name: "Hey Mister", listNum: 5 },
  { src: "songs/His To Keep.mp3", name: "His To Keep", listNum: 5 },
  { src: "songs/Hit A Lick.mp3", name: "Hit A Lick", listNum: 5 },
  { src: "songs/Homicide.mp3", name: "Homicide", listNum: 5 },
  { src: "songs/Horrible.mp3", name: "Horrible", listNum: 5 },
  {
    src: "songs/IDGAF (feat. Juice WRLD) (Sessions).mp3",
    name: "IDGAF (feat. Lil Peep)",
    listNum: 5,
  },
  {
    src: "songs/Inner Peace (Travelling).mp3",
    name: "Inner Peace (Travelling)",
    listNum: 5,
  },
  { src: "songs/In The Moment.mp3", name: "In The Moment", listNum: 5 },
  { src: "songs/In The Air.mp3", name: "In The Air", listNum: 5 },
  {
    src: "songs/Irony (Inspire Me).mp3",
    name: "Irony (Inspire Me)",
    listNum: 5,
  },
  { src: "songs/I Want It (v1).mp3", name: "I Want It (v1)", listNum: 5 },
  {
    src: "songs/It Ain't So (Personification).mp3",
    name: "It Ain't So (Personification)",
    listNum: 5,
  },
  {
    src: "songs/I Wonder (My Mind).mp3",
    name: "I Wonder (My Mind)",
    listNum: 5,
  },
  {
    src: "songs/Kill Benjamin (Money War) (feat. G Herbo).mp3",
    name: "Kill Benjamin (feat. G Herbo)",
    listNum: 5,
  },
  { src: "songs/KKK (2018).mp3", name: "KKK (2018)", listNum: 5 },
  { src: "songs/Kiki (King Kong).mp3", name: "Kiki (King Kong)", listNum: 5 },
  { src: "songs/Life's A Movie.mp3", name: "Life's A Movie", listNum: 5 },
  { src: "songs/Luigi (Twins).mp3", name: "Luigi (Twins)", listNum: 5 },
  { src: "songs/Matte Black.mp3", name: "Matte Black", listNum: 5 },
  { src: "songs/Mental Overload.mp3", name: "Mental Overload", listNum: 5 },
  { src: "songs/Minus.mp3", name: "Minus", listNum: 5 },
  { src: "songs/Money Long.mp3", name: "Money Long", listNum: 5 },
  { src: "songs/Morphine.mp3", name: "Morphine", listNum: 5 },
  { src: "songs/My Bad.mp3", name: "My Bad", listNum: 5 },
  { src: "songs/Narcotics.mp3", name: "Narcotics", listNum: 5 },
  { src: "songs/Never Cared.mp3", name: "Never Cared", listNum: 5 },
  {
    src: "songs/Nobody (feat. Lil Yachty).mp3",
    name: "Nobody (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/No Fears.mp3", name: "No Fears", listNum: 5 },
  { src: "songs/OJ Glove.mp3", name: "OJ Glove", listNum: 5 },
  { src: "songs/On The Regular.mp3", name: "On The Regular", listNum: 5 },
  {
    src: "songs/Oreo (feat. Lil Yachty).mp3",
    name: "Oreo (feat. Lil Yachty)",
    listNum: 5,
  },
  {
    src: "songs/Osama (feat. Lil Yachty).mp3",
    name: "Osama (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/Overseas.mp3", name: "Overseas", listNum: 5 },
  { src: "songs/Pause.mp3", name: "Pause", listNum: 5 },
  { src: "songs/Percs.mp3", name: "Percs", listNum: 5 },
  { src: "songs/Pop Rock.mp3", name: "Pop Rock", listNum: 5 },
  { src: "songs/Pre Heat.mp3", name: "Pre Heat", listNum: 5 },
  { src: "songs/Purple Devil.mp3", name: "Purple Devil", listNum: 5 },
  { src: "songs/Racks In.mp3", name: "Racks In", listNum: 5 },
  { src: "songs/Real One.mp3", name: "Real One", listNum: 5 },
  { src: "songs/Relapse.mp3", name: "Relapse", listNum: 5 },
  { src: "songs/Run A Fade.mp3", name: "Run A Fade", listNum: 5 },
  {
    src: "songs/Semi Addict (Static Shock) (Sessions).mp3",
    name: "Semi Addict (Static Shock) (Sessions)",
    listNum: 5,
  },
  { src: "songs/Set Me Free (v2).mp3", name: "Set Me Free (v2)", listNum: 5 },
  { src: "songs/Sidewalk.mp3", name: "Sidewalk", listNum: 5 },
  { src: "songs/Sky High.mp3", name: "Sky High", listNum: 5 },
  { src: "songs/Slide.mp3", name: "Slide", listNum: 5 },
  { src: "songs/Slow Me Down.mp3", name: "Slow Me Down", listNum: 5 },
  { src: "songs/Snares.mp3", name: "Snares", listNum: 5 },
  { src: "songs/So What.mp3", name: "So What", listNum: 5 },
  { src: "songs/Spanglish.mp3", name: "Spanglish", listNum: 5 },
  {
    src: "songs/Stabbed You (Had To).mp3",
    name: "Stabbed You (Had To)",
    listNum: 5,
  },
  { src: "songs/Starstruck (v3).mp3", name: "Starstruck (v3)", listNum: 5 },
  { src: "songs/Sticks.mp3", name: "Sticks", listNum: 5 },
  { src: "songs/Stranger.mp3", name: "Stranger", listNum: 5 },
  {
    src: "songs/Stumblin' (feat. Lil Yachty).mp3",
    name: "  Stumblin' (feat. Lil Yachty)",
    listNum: 5,
  },
  { src: "songs/Sun (All in).mp3", name: "Sun (All in)", listNum: 5 },
  { src: "songs/Tag.mp3", name: "Tag", listNum: 5 },
  {
    src: "songs/Take Off (Sessions).mp3",
    name: "Take Off (Sessions)",
    listNum: 5,
  },
  {
    src: "songs/Takeover (feat. Lil Yachty).mp3",
    name: "Takeover (feat. Lil Yachty)",
    listNum: 5,
  },
  {
    src: "songs/Talk Too Much (Sessions).mp3",
    name: "Talk Too Much",
    listNum: 5,
  },
  {
    src: "songs/That's A 50 (feat. Playboi Carti).mp3",
    name: "That's A 50 (feat. Playboi Carti)",
    listNum: 5,
  },
  { src: "songs/Thrills.mp3", name: "Thrills", listNum: 5 },
  { src: "songs/Through My Head.mp3", name: "Through My Head", listNum: 5 },
  { src: "songs/Try Me.mp3", name: "Try Me", listNum: 5 },
  { src: "songs/Uh Huh.mp3", name: "Uh Huh", listNum: 5 },
  {
    src: "songs/Want To (feat. Playboi Carti).mp3",
    name: "Want To (feat. Playboi Carti)",
    listNum: 5,
  },
  {
    src: "songs/What Being Rich Feels Like (v2).mp3",
    name: "What Being Rich Feels Like (v2)",
    listNum: 5,
  },
  { src: "songs/What To Think.mp3", name: "What To Think (Dolce)", listNum: 5 },
  {
    src: "songs/Withdrawals.mp3",
    name: "Withdrawals (High Again)",
    listNum: 5,
  },
  { src: "songs/What Else.mp3", name: "What Else", listNum: 5 },
  { src: "songs/Whip (Alaska).mp3", name: "Whip (Alaska)", listNum: 5 },
  { src: "songs/Work Out.mp3", name: "Work Out", listNum: 5 },
  { src: "songs/You.mp3", name: "You", listNum: 5 },
  { src: "songs/Z Nation.mp3", name: "Z Nation", listNum: 5 },
  //#endregion

  { src: "", name: "Exclusives", listNum: 0 }, // Title Button
  //#region Exclusives
  { src: "songs/30 HRS Freestyle.mp3", name: "30 HRS Freestyle", listNum: 7 },
  {
    src: "songs/Autograph (on my line).mp3",
    name: "Autograph (On My Line)",
    listNum: 7,
  },
  { src: "songs/Cali Girl.mp3", name: "Cali Girl", listNum: 7 },
  { src: "songs/Coming Over.mp3", name: "Coming Over", listNum: 7 },
  { src: "songs/Dark Place (Demo).mp3", name: "Dark Place (Demo)", listNum: 7 },
  { src: "songs/Demo Wreck.mp3", name: "Demo Wreck", listNum: 7 },
  { src: "songs/Denial (Demo).mp3", name: "Denial (Demo)", listNum: 7 },
  { src: "songs/Eye Contact.mp3", name: "Eye Contact", listNum: 7 },
  { src: "songs/Forever.mp3", name: "Forever", listNum: 7 },
  { src: "songs/Games.mp3", name: "Games", listNum: 7 },
  { src: "songs/Golden X Get Away.mp3", name: "Golden X Get Away", listNum: 7 },
  {
    src: "songs/Hold Me Down Freestyle.mp3",
    name: "Hold Me Down Freestyle",
    listNum: 7,
  },
  { src: "songs/Hollywood Dreams.mp3", name: "Hollywood Dreams", listNum: 7 },
  { src: "songs/How Dat Go.mp3", name: "How Dat Go", listNum: 7 },
  { src: "songs/I Know One Thing.mp3", name: "I Know One Thing", listNum: 7 },
  { src: "songs/KNOW US.mp3", name: "KNOW US", listNum: 7 },
  { src: "songs/MOVES Freestyle.mp3", name: "MOVES Freestyle", listNum: 7 },
  { src: "songs/My Fault.mp3", name: "My Fault", listNum: 7 },
  {
    src: "songs/Never Have To Flex Freestyle.mp3",
    name: "Never Have To Flex Freestyle",
    listNum: 7,
  },
  { src: "songs/On My Mind.mp3", name: "On My Mind", listNum: 7 },
  { src: "songs/PARANOID (PROD. NICK MIRA).mp3", name: "PARANOID", listNum: 7 },
  { src: "songs/Rainbow.mp3", name: "Rainbow", listNum: 7 },
  { src: "songs/ROCKSTAR GIRL.mp3", name: "ROCKSTAR GIRL", listNum: 7 },
  { src: "songs/RUN.mp3", name: "RUN", listNum: 7 },
  {
    src: "songs/Slick Rick Freestyle.mp3",
    name: "Slick Rick Freestyle",
    listNum: 7,
  },
  { src: "songs/Something New.mp3", name: "Something New", listNum: 7 },
  {
    src: "songs/This Cant Be Happening.mp3",
    name: "This Cant Be Happening",
    listNum: 7,
  },
  {
    src: "songs/Until It's Over (Closure).mp3",
    name: "Until It's Over (Closure)",
    listNum: 7,
  },
  { src: "songs/You Don't Love Me.mp3", name: "You Don't Love Me", listNum: 7 },
  //#endregion

  { src: "", name: "JW3", listNum: 0 }, // Title Button (-1 because its at the top of the page and needs a unique id)
  //#region JW3
  // New
  { src: "songs/Chase My Thrills.mp3", name: "Chase My Thrills", listNum: 1 },
  { src: "songs/Classy.mp3", name: "Classy", listNum: 1 },
  { src: "songs/Get Excited.mp3", name: "Get Excited", listNum: 1 },
  { src: "songs/Go Away.mp3", name: "Go Away", listNum: 1 },
  { src: "songs/Maserati.mp3", name: "Maserati", listNum: 1 },
  { src: "songs/No Stopping Us.mp3", name: "No Stopping Us", listNum: 1 },
  { src: "songs/Not Ashamed.mp3", name: "Not Ashamed", listNum: 1 },
  { src: "songs/Pray For Me.mp3", name: "Pray For Me", listNum: 1 },
  { src: "songs/Saved By The Bell.mp3", name: "Saved By The Bell", listNum: 1 },
  { src: "songs/Paranoia Highs (USD).mp3", name: "USD", listNum: 1 },
  { src: "songs/Watcha On.mp3", name: "Watcha On", listNum: 1 },

  { src: "songs/38 Special.mp3", name: ".38 Special", listNum: 1 },
  { src: "songs/Adore You.mp3", name: "Adore You", listNum: 1 },
  {
    src: "songs/All Alone (On My Own).mp3",
    name: "All Alone (On My Own)",
    listNum: 1,
  },
  {
    src: "songs/Another Thing To Do It.mp3",
    name: "Another Thing To Do It",
    listNum: 1,
  },
  {
    src: "songs/Lock On (Dark Arts).mp3",
    name: "Barry Bonds (Dark Arts)",
    listNum: 1,
  },
  {
    src: "songs/Been Through Hell (Met in September).mp3",
    name: "Been Through Hell",
    listNum: 1,
  },
  {
    src: "songs/Betray My Trust (v2) (feat. iLoveMakonnen).mp3",
    name: "Betray My Trust (feat. iLoveMakonnen)",
    listNum: 1,
  },
  {
    src: "songs/Bitty (feat. Trippie Redd).mp3",
    name: "Bitty (feat. Trippie Redd)",
    listNum: 1,
  },
  {
    src: "songs/Biscotti In The Air.mp3",
    name: "Biscotti In The Air",
    listNum: 1,
  },
  { src: "songs/Bloody Blade.mp3", name: "Bloody Blade", listNum: 1 },
  { src: "songs/Californication.mp3", name: "Californication", listNum: 1 },
  { src: "songs/Can't Be Saved.mp3", name: "Can't Be Saved", listNum: 1 },
  { src: "songs/Carry It.mp3", name: "Carry It", listNum: 1 },
  { src: "songs/Chrome.mp3", name: "Chrome", listNum: 1 },
  { src: "songs/Coraline.mp3", name: "Coraline", listNum: 1 },
  { src: "songs/Cursed Heart.mp3", name: "Cursed Heart", listNum: 1 },
  {
    src: "songs/Dark Thoughts (On Your Mind).mp3",
    name: "Dark Thoughts (On Your Mind)",
    listNum: 1,
  },
  { src: "songs/Day One (v2).mp3", name: "Day One (v2)", listNum: 1 },
  { src: "songs/Demise.mp3", name: "Bloody Blade", listNum: 1 },
  { src: "songs/Die To Live.mp3", name: "Die To Live", listNum: 1 },
  {
    src: "songs/Door (feat. Chance The Rapper).mp3",
    name: "Door (feat. Chance The Rapper)",
    listNum: 1,
  },
  {
    src: "songs/Drugs Are My Friends.mp3",
    name: "Drugs Are My Friends",
    listNum: 1,
  },
  { src: "songs/Fire In My Lungs.mp3", name: "Fire In My Lungs", listNum: 1 },
  { src: "songs/Flight To London.mp3", name: "Flight To London", listNum: 1 },
  { src: "songs/Floor It.mp3", name: "Floor It", listNum: 1 },
  { src: "songs/Don't Forget Me.mp3", name: "Forget Me Not", listNum: 1 },
  { src: "songs/Forever Love.mp3", name: "Forever Love", listNum: 1 },
  {
    src: "songs/Good Times (feat. Kid Cudi).mp3",
    name: "Good Times (feat. Kid Cudi)",
    listNum: 1,
  },
  { src: "songs/Gone.mp3", name: "Gone", listNum: 1 },
  { src: "songs/GoPro.mp3", name: "GoPro", listNum: 1 },
  { src: "songs/Glock Handler.mp3", name: "Glock Handler", listNum: 1 },
  { src: "songs/Hard To Digest.mp3", name: "Hard To Digest", listNum: 1 },
  { src: "songs/Heroine Music.mp3", name: "Heroine Music", listNum: 1 },
  { src: "songs/High Tide.mp3", name: "High Tide", listNum: 1 },
  { src: "songs/Home.mp3", name: "Home", listNum: 1 },
  {
    src: "songs/Home (feat. LAROI).mp3",
    name: "Home (feat. LAROI)",
    listNum: 1,
  },
  { src: "songs/I Wonder.mp3", name: "I Wonder", listNum: 1 },
  {
    src: "songs/Infared (with Trippie Redd).mp3",
    name: "Infared (with Trippie Redd)",
    listNum: 1,
  },
  { src: "songs/K Like A Russian.mp3", name: "K Like A Russian", listNum: 1 },
  { src: "songs/Karate Kid.mp3", name: "Karate Kid", listNum: 1 },
  { src: "songs/Keep It.mp3", name: "Keep It", listNum: 1 },
  {
    src: "songs/On The Road.mp3",
    name: "Let It Off (On The Road)",
    listNum: 1,
  },
  {
    src: "songs/Let Me Be (Lone Ranger).mp3",
    name: "Let Me Be (Lone Ranger)",
    listNum: 1,
  },
  { src: "songs/Life's A Dungeon.mp3", name: "Life's A Dungeon", listNum: 1 },
  {
    src: "songs/Living At The Top (Simple).mp3",
    name: "Living At The Top (Simple)",
    listNum: 1,
  },
  {
    src: "songs/London (Interlude).mp3",
    name: "London (Interlude)",
    listNum: 1,
  },
  { src: "songs/Long Time Coming.mp3", name: "Long Time Coming", listNum: 1 },
  { src: "songs/Lullabies.mp3", name: "Lullabies", listNum: 1 },
  { src: "songs/Made It Work.mp3", name: "Made It Work", listNum: 1 },
  {
    src: "songs/Man Down (Rockstar Boy).mp3",
    name: "Man Down (Rockstar Boy)",
    listNum: 1,
  },
  { src: "songs/Murder Rate.mp3", name: "Murder Rate", listNum: 1 },
  { src: "songs/My Year.mp3", name: "My Year", listNum: 1 },
  { src: "songs/NLMB (Oh Dear).mp3", name: "NLMB (Oh Dear)", listNum: 1 },
  { src: "songs/No Laces.mp3", name: "No Laces", listNum: 1 },
  { src: "songs/No Trespassing.mp3", name: "No Trespassing", listNum: 1 },
  { src: "songs/No Wrong.mp3", name: "No Wrong", listNum: 1 },
  { src: "songs/On Time.mp3", name: "On Time", listNum: 1 },
  { src: "songs/Overseer.mp3", name: "Overseer (Omen)", listNum: 1 },
  { src: "songs/Oversprung.mp3", name: "Over Sprung", listNum: 1 },
  {
    src: "songs/Priceless (Wraith).mp3",
    name: "Priceless (Wraith)",
    listNum: 1,
  },
  { src: "songs/Purple Ocean.mp3", name: "Purple Ocean", listNum: 1 },
  { src: "songs/Purple Substance.mp3", name: "Purple Substance", listNum: 1 },
  { src: "songs/Rain Dance.mp3", name: "Rain Dance", listNum: 1 },
  { src: "songs/Reason.mp3", name: "Reason", listNum: 1 },
  { src: "songs/Red Moonlight.mp3", name: "Red Moonlight", listNum: 1 },
  { src: "songs/Rich Forever.mp3", name: "Rich Forever", listNum: 1 },
  { src: "songs/Rikers.mp3", name: "Rikers", listNum: 1 },
  {
    src: "songs/Scarface (feat. Gunna).mp3",
    name: "Scarface (feat. Gunna)",
    listNum: 1,
  },
  { src: "songs/Shot Em Down.mp3", name: "Shot Em Down", listNum: 1 },
  {
    src: "songs/Soda Pop (feat. Roddy Ricch).mp3",
    name: "Soda Pop (feat. Roddy Ricch)",
    listNum: 1,
  },
  { src: "songs/Speed Me Up.mp3", name: "Speed Me Up", listNum: 1 },
  {
    src: "songs/Split My Brain (808 Freestyle).mp3",
    name: "Split My Brain (808 Freestyle)",
    listNum: 1,
  },
  { src: "songs/Swear.mp3", name: "Swear", listNum: 1 },
  { src: "songs/Take My Soul.mp3", name: "Take My Soul", listNum: 1 },
  { src: "songs/Tattoos And Ink.mp3", name: "Tattoos And Ink", listNum: 1 },
  {
    src: "songs/Unexplainable.mp3",
    name: "Unexplainable (feat. The Kid LAROI)",
    listNum: 1,
  },
  { src: "songs/Until I Die.mp3", name: "Until I Die", listNum: 1 },
  { src: "songs/My Way Home (Pt. 2).mp3", name: "Used And Abused", listNum: 1 },
  { src: "songs/Way Too Many.mp3", name: "Way Too Many", listNum: 1 },
  {
    src: "songs/We Don't Get Along.mp3",
    name: "We Don't Get Along",
    listNum: 1,
  },
  {
    src: "songs/What's Brakkin' (feat. Offset).mp3",
    name: "What's Brakkin' (feat. Offset)",
    listNum: 1,
  },
  { src: "songs/X-Mas List.mp3", name: "X-Mas List", listNum: 1 },
  { src: "songs/Zoom.mp3", name: "Zoom", listNum: 1 },
  //#endregion

  { src: "", name: "DRFL", listNum: 0 }, // Title Button
  //#region DRFL
  // New Songs
  { src: "songs/Afterlife.mp3", name: "Afterlife", listNum: 2 },
  { src: "songs/Chase My Highs.mp3", name: "Chase My Highs", listNum: 2 },
  { src: "songs/Happy Life.mp3", name: "Happy Life", listNum: 2 },
  {
    src: "songs/Her And Her Beauty.mp3",
    name: "Her And Her Beauty",
    listNum: 2,
  },
  {
    src: "songs/Hold It Down (Highschool).mp3",
    name: "Hold It Down (Highschool)",
    listNum: 2,
  },
  { src: "songs/Hope I Did It.mp3", name: "Hope I Did It", listNum: 2 },
  { src: "songs/Lost In My Head.mp3", name: "Lost In My Head", listNum: 2 },
  { src: "songs/Road Rage.mp3", name: "Road Rage", listNum: 2 },

  { src: "songs/2019 My Year.mp3", name: "2019 My Year", listNum: 2 },
  { src: "songs/4 Instance.mp3", name: "4 Instance", listNum: 2 },
  { src: "songs/70s.mp3", name: "'70s", listNum: 2 },
  {
    src: "songs/90210 (Speed Demon).mp3",
    name: "90210 (Speed Demon)",
    listNum: 2,
  },
  { src: "songs/All Talk.mp3", name: "All Talk", listNum: 2 },
  { src: "songs/Another One.mp3", name: "Another One", listNum: 2 },
  { src: "songs/Anxiety.mp3", name: "Anxiety", listNum: 2 },
  { src: "songs/Astray.mp3", name: "Astray", listNum: 2 },
  { src: "songs/Attachments.mp3", name: "Attachments", listNum: 2 },
  {
    src: "songs/Baguettes (feat. Juice WRLD).mp3",
    name: "Baguettes (feat. Juice WRLD)",
    listNum: 2,
  },
  {
    src: "songs/Barbarian (Vandal).mp3",
    name: "Barbarian (Vandal)",
    listNum: 2,
  },
  {
    src: "songs/Best Around (Racks Out).mp3",
    name: "Best Around (Racks Out)",
    listNum: 2,
  },
  {
    src: "songs/Best Of 'Em (Western).mp3",
    name: "Best Of 'Em (Western)",
    listNum: 2,
  },
  { src: "songs/Better Off Alone.mp3", name: "Better Off Alone", listNum: 2 },
  { src: "songs/Big Dog.mp3", name: "Big Dog", listNum: 2 },
  { src: "songs/Bonjour (On Tour).mp3", name: "Bonjour (On Tour)", listNum: 2 },
  { src: "songs/Boss Of Me.mp3", name: "Boss Of Me", listNum: 2 },
  {
    src: "songs/Bye Bye Baby (feat. Young Thug).mp3",
    name: "Bye Bye Baby (feat. Young Thug)",
    listNum: 2,
  },
  { src: "songs/Attachments.mp3", name: "Attachments", listNum: 2 },
  {
    src: "songs/Cha-Ching (Spend It All).mp3",
    name: "Cha-Ching (Spend It All)",
    listNum: 2,
  },
  { src: "songs/Iron On Me.mp3", name: "Challenger (Iron On Me)", listNum: 2 },
  { src: "songs/Codeine Cobain.mp3", name: "Codeine Cobain", listNum: 2 },
  { src: "songs/Scarface (Cold Summer).mp3", name: "Cold Summer", listNum: 2 },
  { src: "songs/Condone It.mp3", name: "Condone It", listNum: 2 },
  { src: "songs/Confide.mp3", name: "Confide", listNum: 2 },
  { src: "songs/Won't Die (Conjuring).mp3", name: "Conjuring", listNum: 2 },
  {
    src: "songs/Contained (Change).mp3",
    name: "Contained (Change)",
    listNum: 2,
  },
  { src: "songs/Cursed.mp3", name: "Cursed", listNum: 2 },
  { src: "songs/Kurtis Blow.mp3", name: "Kurtis Blow", listNum: 2 },
  { src: "songs/Dome.mp3", name: "Dome", listNum: 2 },
  {
    src: "songs/Do The Most (No Coaster).mp3",
    name: "Do The Most (No Coaster)",
    listNum: 2,
  },
  { src: "songs/Draco On Me.mp3", name: "Draco On Me", listNum: 2 },
  { src: "songs/Ducks.mp3", name: "Ducks", listNum: 2 },
  { src: "songs/Elevate.mp3", name: "Elevate", listNum: 2 },
  { src: "songs/Evil Twins.mp3", name: "Evil Twins", listNum: 2 },
  { src: "songs/Fire.mp3", name: "Fire", listNum: 2 },
  { src: "songs/From Afar.mp3", name: "From Afar", listNum: 2 },
  { src: "songs/Get Geeked.mp3", name: "Get Geeked", listNum: 2 },
  { src: "songs/Get Over.mp3", name: "Get Over", listNum: 2 },
  { src: "songs/Give Me My Fix.mp3", name: "Give Me My Fix", listNum: 2 },
  { src: "songs/Hi Tech Top.mp3", name: "Hi Tech Top", listNum: 2 },
  { src: "songs/Impatient.mp3", name: "Impatient", listNum: 2 },
  {
    src: "songs/Issues (Hit) (feat. G Herbo).mp3",
    name: "Issues (feat. G Herbo)",
    listNum: 2,
  },
  { src: "songs/In The Summer.mp3", name: "In The Summer", listNum: 2 },
  { src: "songs/Jack & Jill.mp3", name: "Jack & Jill", listNum: 2 },
  { src: "songs/KTM Drip.mp3", name: "KTM Drip", listNum: 2 },
  {
    src: "songs/Late Night (Amazing).mp3",
    name: "Late Night (Amazing)",
    listNum: 2,
  },
  {
    src: "songs/Late Night Thoughts.mp3",
    name: "Late Night Thoughts",
    listNum: 2,
  },
  { src: "songs/Lock Box.mp3", name: "Lock Box", listNum: 2 },
  {
    src: "songs/Lost Too Many (Goblin).mp3",
    name: "Lost Too Many (Goblin)",
    listNum: 2,
  },
  { src: "songs/Love Story.mp3", name: "Love Story", listNum: 2 },
  { src: "songs/Lurkin (Sessions).mp3", name: "Lurkin (Sessions)", listNum: 2 },
  { src: "songs/Make No Noise.mp3", name: "Make No Noise", listNum: 2 },
  { src: "songs/Mama Said.mp3", name: "Mama Said", listNum: 2 },
  { src: "songs/Mansion.mp3", name: "Mansion", listNum: 2 },
  {
    src: "songs/McLaren Drive (Tic-Tac-Toe).mp3",
    name: "McLaren Drive (Tic-Tac-Toe)",
    listNum: 2,
  },
  {
    src: "songs/Misery Avenue (v3).mp3",
    name: "Misery Avenue (v3)",
    listNum: 2,
  },
  { src: "songs/Nuts Itch.mp3", name: "Nuts Itch", listNum: 2 },
  { src: "songs/Moncler Year.mp3", name: "Moncler Year", listNum: 2 },
  {
    src: "songs/Mr. Freeze (Fleur De Lis).mp3",
    name: "Mr. Freeze (Fleur De Lis)",
    listNum: 2,
  },
  {
    src: "songs/My Gang (Together).mp3",
    name: "My Gang (Together)",
    listNum: 2,
  },
  { src: "songs/Off The Rip.mp3", name: "Off The Rip", listNum: 2 },
  { src: "songs/Out The Projects.mp3", name: "Out The Projects", listNum: 2 },
  {
    src: "songs/Pesos (Troubled Kids).mp3",
    name: "Pesos (Troubled Kids)",
    listNum: 2,
  },
  { src: "songs/Pieces.mp3", name: "Pieces", listNum: 2 },
  {
    src: "songs/Pop It (feat. G Herbo).mp3",
    name: "Pop It (feat. G Herbo)",
    listNum: 2,
  },
  { src: "songs/Purple Moncler.mp3", name: "Purple Moncler", listNum: 2 },
  {
    src: "songs/Range (feat. G Herbo).mp3",
    name: "Range (feat. G Herbo)",
    listNum: 2,
  },
  {
    src: "songs/Rental (Cha-Ching).mp3",
    name: "Rental (Cha-Ching)",
    listNum: 2,
  },
  {
    src: "songs/Red Dead Redemption.mp3",
    name: "Red Dead Redemption",
    listNum: 2,
  },
  { src: "songs/Rims.mp3", name: "Rims", listNum: 2 },
  { src: "songs/Road Runners.mp3", name: "Road Runners", listNum: 2 },
  { src: "songs/Sexual Healing.mp3", name: "Sexual Healing", listNum: 2 },
  { src: "songs/Singalong.mp3", name: "Singalong", listNum: 2 },
  {
    src: "songs/Stargazing (Not An Option).mp3",
    name: "Stargazing (Not An Option)",
    listNum: 2,
  },
  {
    src: "songs/Starstruck (feat. Mark Hoppus).mp3",
    name: "Starstruck (feat. Mark Hoppus)",
    listNum: 2,
  },
  {
    src: "songs/Stick Talk (Lavagirl).mp3",
    name: "Stick Talk (Lavagirl)",
    listNum: 2,
  },
  { src: "songs/Stuck In My Ways.mp3", name: "Stuck In My Ways", listNum: 2 },
  { src: "songs/Under Her Skin.mp3", name: "Under Her Skin", listNum: 2 },
  { src: "songs/Victorious.mp3", name: "Victorious", listNum: 2 },
  { src: "songs/VLone Thugs.mp3", name: "VLone Thugs", listNum: 2 },
  { src: "songs/Void.mp3", name: "Void", listNum: 2 },
  { src: "songs/Wake Up.mp3", name: "Wake Up", listNum: 2 },
  {
    src: "songs/Damn Right.mp3",
    name: "What I Wanna Do (Damn Right)",
    listNum: 2,
  },
  { src: "songs/Willing To Die.mp3", name: "Willing To Die", listNum: 2 },
  { src: "songs/Worth It.mp3", name: "Worth It", listNum: 2 },
  //#endregion

  { src: "", name: "GB&GR", listNum: 0 }, // Title Button
  //#region GB&GR
  {
    src: "songs/Chemical Imbalance (Sessions).mp3",
    name: "Chemical Imbalance",
    listNum: 3,
  },
  {
    src: "songs/Curse from an Angel.mp3",
    name: "Curse from an Angel",
    listNum: 3,
  },
  {
    src: "songs/Love Over There (v2).mp3",
    name: "Walking In The Sand",
    listNum: 3,
  },
  { src: "songs/On Me.mp3", name: "On Me", listNum: 3 },
  { src: "songs/Start It Up.mp3", name: "Start It Up", listNum: 3 },
  {
    src: "songs/Thousand Cliffs (Intended).mp3",
    name: "Thousand Cliffs (Intended)",
    listNum: 3,
  },
  { src: "songs/27 Club.mp3", name: "27 Club", listNum: 3 },
  { src: "songs/6.mp3", name: "6", listNum: 3 },
  { src: "songs/Addicted.mp3", name: "Addicted", listNum: 3 },
  {
    src: "songs/Airport Security.mp3",
    name: "Airport Security (feat. Lil Yachty)",
    listNum: 3,
  },
  { src: "songs/Analog.mp3", name: "Analog", listNum: 3 },
  { src: "songs/Back In Chicago.mp3", name: "Back In Chicago", listNum: 3 },
  { src: "songs/Bad Romance.mp3", name: "Bad Romance", listNum: 3 },
  { src: "songs/Ball (Larry Bird).mp3", name: "Ball (Larry Bird)", listNum: 3 },
  { src: "songs/Bank Account.mp3", name: "Bank Account", listNum: 3 },
  { src: "songs/Been A While.mp3", name: "Been Awhile", listNum: 3 },
  { src: "songs/Bentley Truck.mp3", name: "Bentley Truck", listNum: 3 },
  {
    src: "songs/Billy Idol (Mary Jane).mp3",
    name: "Billy Idol (Mary Jane)",
    listNum: 3,
  },
  { src: "songs/Bottle.mp3", name: "Bottle", listNum: 3 },
  { src: "songs/Boy Wit Da Bandz.mp3", name: "Boy Wit Da Bandz", listNum: 3 },
  {
    src: "songs/Bullet For My Valentine.mp3",
    name: "Bullet For My Valentine",
    listNum: 3,
  },
  { src: "songs/Can't Survive.mp3", name: "Can't Survive", listNum: 3 },
  { src: "songs/Codeine Casket.mp3", name: "Codeine Casket", listNum: 3 },
  { src: "songs/Chase You Down.mp3", name: "Chase You Down", listNum: 3 },
  { src: "songs/Chimp.mp3", name: "Chimp", listNum: 3 },
  {
    src: "songs/Choppa (feat. D Savage).mp3",
    name: "Choppa (feat. D Savage)",
    listNum: 3,
  },
  { src: "songs/Codeiner.mp3", name: "Codeiner", listNum: 3 },
  { src: "songs/Come Around.mp3", name: "Come Around", listNum: 3 },
  { src: "songs/Complications.mp3", name: "Complications", listNum: 3 },
  { src: "songs/Confessions.mp3", name: "Confessions", listNum: 3 },
  { src: "songs/Crazy Things.mp3", name: "Crazy Things", listNum: 3 },
  { src: "songs/Crossing The Line.mp3", name: "Crossing The Line", listNum: 3 },
  {
    src: "songs/Dagger (feat. MadeInTYO).mp3",
    name: "Dagger (feat. MadeInTYO)",
    listNum: 3,
  },
  {
    src: "songs/Death Penalty (Dark Queen).mp3",
    name: "Death Penalty (Dark Queen)",
    listNum: 3,
  },
  { src: "songs/Demon Love (v2).mp3", name: "Demon Love (v2)", listNum: 3 },
  { src: "songs/Deprived.mp3", name: "Deprived", listNum: 3 },
  { src: "songs/Devil Horns.mp3", name: "Devil Horns", listNum: 3 },
  { src: "songs/Drown.mp3", name: "Drown", listNum: 3 },
  { src: "songs/Dumb Slut.mp3", name: "Dumb ****", listNum: 3 },
  { src: "songs/Dummy.mp3", name: "Dummy", listNum: 3 },
  {
    src: "songs/Emotional Overdose.mp3",
    name: "Emotional Overdose",
    listNum: 3,
  },
  { src: "songs/Everlasting Love.mp3", name: "Everlasting Love", listNum: 3 },
  { src: "songs/Eyes Closed.mp3", name: "Eyes Closed", listNum: 3 },
  { src: "songs/Eyes Up.mp3", name: "Eyes Up", listNum: 3 },
  { src: "songs/Fall v1.mp3", name: "Fall (v1)", listNum: 3 },
  { src: "songs/Fenty (Let It Go).mp3", name: "Fenty (Let It Go)", listNum: 3 },
  { src: "songs/Fever.mp3", name: "Fever", listNum: 3 },
  { src: "songs/Flavor.mp3", name: "Flavor", listNum: 3 },
  { src: "songs/Flaws.mp3", name: "Flaws", listNum: 3 },
  {
    src: "songs/Forever (Left You).mp3",
    name: "Forever (Left You)",
    listNum: 3,
  },
  { src: "songs/From The Bottom.mp3", name: "From The Bottom", listNum: 3 },
  { src: "songs/From The Start.mp3", name: "From The Start", listNum: 3 },
  { src: "songs/Game.mp3", name: "Game", listNum: 3 },
  { src: "songs/Girlfriend.mp3", name: "Girlfriend", listNum: 3 },
  { src: "songs/Goyard Bag.mp3", name: "Goyard Bag", listNum: 3 },
  { src: "songs/Grace.mp3", name: "Grace", listNum: 3 },
  { src: "songs/Gucci Purse.mp3", name: "Gucci Purse", listNum: 3 },
  { src: "songs/Hate Her Friends.mp3", name: "Hate Her Friends", listNum: 3 },
  { src: "songs/Heart Exposure.mp3", name: "Heart Exposure", listNum: 3 },
  { src: "songs/Heavy.mp3", name: "Heavy", listNum: 3 },
  { src: "songs/Here We Go Again.mp3", name: "Here We Go Again", listNum: 3 },
  { src: "songs/Hey Wonderland.mp3", name: "Hey Wonderland", listNum: 3 },
  {
    src: "songs/Swisher (Hilfiger).mp3",
    name: "Hilfiger (Swisher)",
    listNum: 3,
  },
  { src: "songs/Hold My Hand.mp3", name: "Hold My Hand", listNum: 3 },
  { src: "songs/Hunnid.mp3", name: "Hunnid", listNum: 3 },
  { src: "songs/Hypnotic.mp3", name: "Hypnotic", listNum: 3 },
  { src: "songs/Irony.mp3", name: "Irony", listNum: 3 },
  { src: "songs/Jeffery.mp3", name: "Jeffery", listNum: 3 },
  { src: "songs/Juicy.mp3", name: "Juicy", listNum: 3 },
  { src: "songs/Junkie.mp3", name: "Junkie", listNum: 3 },
  { src: "songs/Kickflip.mp3", name: "Kickflip", listNum: 3 },
  { src: "songs/Kirby's Selecta.mp3", name: "Kirby's Selecta", listNum: 3 },
  { src: "songs/Latex.mp3", name: "Latex", listNum: 3 },
  { src: "songs/Lavish.mp3", name: "Lavish", listNum: 3 },
  { src: "songs/Lean Wit Me (v2).mp3", name: "Lean Wit Me (v2)", listNum: 3 },
  { src: "songs/Left 4 Dead.mp3", name: "Left 4 Dead", listNum: 3 },
  { src: "songs/Live Forever.mp3", name: "Live Forever", listNum: 3 },
  { src: "songs/London Tipton.mp3", name: "London Tipton", listNum: 3 },
  { src: "songs/Lonely.mp3", name: "Lonely", listNum: 3 },
  { src: "songs/Love Cage.mp3", name: "Love Cage", listNum: 3 },
  { src: "songs/Love Over There.mp3", name: "Love Over There", listNum: 3 },
  { src: "songs/Love Story.mp3", name: "Love Story", listNum: 3 },
  { src: "songs/Meadows.mp3", name: "Meadows", listNum: 3 },
  { src: "songs/Molly & Mike.mp3", name: "Molly & Mike", listNum: 3 },
  { src: "songs/Naruto.mp3", name: "Naruto", listNum: 3 },
  { src: "songs/Nesquick.mp3", name: "Nesquick", listNum: 3 },
  { src: "songs/No Depot (Nemo).mp3", name: "No Depot (Nemo)", listNum: 3 },
  { src: "songs/Orange.mp3", name: "Orange", listNum: 3 },
  { src: "songs/Quitter.mp3", name: "Quitter", listNum: 3 },
  {
    src: "songs/Remind Me Of The Summer.mp3",
    name: "Remind Me Of The Summer",
    listNum: 3,
  },
  { src: "songs/Percaholic.mp3", name: "Percaholic", listNum: 3 },
  { src: "songs/Potions.mp3", name: "Potions", listNum: 3 },
  { src: "songs/Slasher.mp3", name: "Slasher", listNum: 3 },
  { src: "songs/Sleep Paralysis.mp3", name: "Sleep Paralysis", listNum: 3 },
  { src: "songs/So Fast.mp3", name: "Drivin' So Fast", listNum: 3 },
  { src: "songs/Not Sorry.mp3", name: "Not Sorry", listNum: 3 },
  { src: "songs/Numb The Pain.mp3", name: "Numb The Pain", listNum: 3 },
  {
    src: "songs/Tales Of The Toxic.mp3",
    name: "Tales Of The Toxic",
    listNum: 3,
  },
  {
    src: "songs/Mr. Heartbreak (v3).mp3",
    name: "Mr. Heartbreak (v3)",
    listNum: 3,
  },
  {
    src: "songs/My Phone (Sessions).mp3",
    name: "My Phone (Sessions)",
    listNum: 3,
  },
  {
    src: "songs/Nascar (feat. 147 Calboy).mp3",
    name: "Nascar (feat. 147 Calboy)",
    listNum: 3,
  },
  { src: "songs/No Benefits.mp3", name: "No Benefits", listNum: 3 },
  { src: "songs/Perc Floating.mp3", name: "Perc Floating", listNum: 3 },
  { src: "songs/Plug.mp3", name: "Plug", listNum: 3 },
  {
    src: "songs/Psychedelic (Feeling Myself).mp3",
    name: "Psychedelic (Feeling Myself)",
    listNum: 3,
  },
  { src: "songs/Python.mp3", name: "Python", listNum: 3 },
  { src: "songs/Right Or Wrong.mp3", name: "Right Or Wrong", listNum: 3 },
  { src: "songs/Scars.mp3", name: "Scars", listNum: 3 },
  {
    src: "songs/Show Me Love (27 Club).mp3",
    name: "Show Me Love (27 Club)",
    listNum: 3,
  },
  { src: "songs/Slenderman.mp3", name: "Slenderman", listNum: 3 },
  {
    src: "songs/To The Grave (Feelings).mp3",
    name: "To The Grave (Feelings)",
    listNum: 3,
  },
  {
    src: "songs/Tonight (feat. Valee).mp3",
    name: "Tonight (feat. Valee)",
    listNum: 3,
  },
  {
    src: "songs/Trap Phone (feat. G Herbo).mp3",
    name: "Trap Phone (feat. G Herbo)",
    listNum: 3,
  },
  { src: "songs/Trees.mp3", name: "Trees", listNum: 3 },
  { src: "songs/Trick Or Treat.mp3", name: "Trick Or Treat", listNum: 3 },
  { src: "songs/Uncertain Shadows.mp3", name: "Uncertain Shadows", listNum: 3 },
  { src: "songs/Wavy.mp3", name: "Wavy", listNum: 3 },
  //#endregion

  { src: "", name: "999", listNum: 0 }, // Title Button
  //#region 999
  // New Songs
  { src: "songs/Going MIA.mp3", name: "Going MIA", listNum: 4 },
  { src: "songs/Believe In Me.mp3", name: "Believe In Me", listNum: 4 },

  { src: "songs/All Burnt Up.mp3", name: "All Burnt Up", listNum: 4 },
  { src: "songs/Already (v1).mp3", name: "Already (v1)", listNum: 4 },
  { src: "songs/Faded (Oh No).mp3", name: "Faded (Oh No)", listNum: 4 },
  {
    src: "songs/Hell (feat DMG Mthang).mp3",
    name: "Hell (feat DMG Mthang)",
    listNum: 4,
  },
  { src: "songs/Hennessy.mp3", name: "Hennessy", listNum: 4 },
  { src: "songs/Kawasaki.mp3", name: "Kawasaki", listNum: 4 },
  { src: "songs/Love No Hoe.mp3", name: "Love No Hoe", listNum: 4 },
  { src: "songs/Make It Sell.mp3", name: "Make It Sell", listNum: 4 },
  { src: "songs/Mind Games.mp3", name: "Mind Games", listNum: 4 },
  { src: "songs/Monster.mp3", name: "Monster", listNum: 4 },
  { src: "songs/No More.mp3", name: "No More", listNum: 4 },
  { src: "songs/No Vanity.mp3", name: "No Vanity", listNum: 4 },
  { src: "songs/On & On.mp3", name: "On & On", listNum: 4 },
  { src: "songs/Rock.mp3", name: "Rock", listNum: 4 },
  { src: "songs/Triple 9 (999).mp3", name: "Triple 9 (999)", listNum: 4 },
  { src: "songs/Your Man (France).mp3", name: "Your Man (France)", listNum: 4 },
  //#endregion

  { src: "", name: "JTK", listNum: 0 }, // Title Button
  //#region JTK
  // New Songs
  {
    src: "songs/Xan Xan Xan (XXX) ft GDo.mp3",
    name: "Xan Xan Xan (XXX) ft GDo",
    listNum: 8,
  },
  { src: "songs/Right Left.mp3", name: "Right Left", listNum: 8 },

  { src: "songs/Aye Aye.mp3", name: "Aye Aye", listNum: 8 },
  { src: "songs/Blowing Up.mp3", name: "Blowing Up", listNum: 8 },
  { src: "songs/Different Phases.mp3", name: "Different Phases", listNum: 8 },
  {
    src: "songs/Forever (Mrs. Miracle).mp3",
    name: "Forever (Mrs. Miracle)",
    listNum: 8,
  },
  { src: "songs/I Don't Know.mp3", name: "I Don't Know", listNum: 8 },
  {
    src: "songs/Lavender Town (feat. Zay Loco).mp3",
    name: "Lavender Town",
    listNum: 8,
  },
  { src: "songs/No Reason.mp3", name: "No Reason", listNum: 8 },
  { src: "songs/Oh My Oh My.mp3", name: "Oh My Oh My", listNum: 8 },
  {
    src: "songs/On The Rise (Count My Dough).mp3",
    name: "On The Rise",
    listNum: 8,
  },
  { src: "songs/Over & Over.mp3", name: "Over & Over", listNum: 8 },
  { src: "songs/Pesos.mp3", name: "Pesos", listNum: 8 },
  { src: "songs/Ran Off.mp3", name: "Ran Off", listNum: 8 },
  { src: "songs/Thoughts.mp3", name: "Thoughts", listNum: 8 },
  { src: "songs/Surfin'.mp3", name: "Surfin'", listNum: 8 },
  { src: "songs/Who Are You.mp3", name: "Who Are You", listNum: 8 },
  //#endregion

  { src: "", name: "Other", listNum: 0 }, // Title Button
  //#region Unknown
  // New Songs
  { src: "songs/Dark Tints.mp3", name: "Dark Tints", listNum: 9 },
  {
    src: "songs/Forever ft Ty Dolla $ign.mp3",
    name: "Forever ft Ty Dolla $ign",
    listNum: 9,
  },
  { src: "songs/Late Night.mp3", name: "Late Night", listNum: 9 },
  { src: "songs/Clout.mp3", name: "Clout", listNum: 9 },

  { src: "songs/Dropout.mp3", name: "Dropout", listNum: 6 }, // 2017
  { src: "songs/Let's Go.mp3", name: "Let's Go", listNum: 6 }, // Not sure
  { src: "songs/Maybe (Master).mp3", name: "Maybe (Master)", listNum: 6 }, // Stem
  {
    src: "songs/Only You On My Mind.mp3",
    name: "Only You On My Mind",
    listNum: 6,
  }, // 2017

  //#endregion
];

// Export the songs array for use in other scripts
export default songlist;
