// Define an array of songs with their paths and names
const songlist = [
  { src: "songs/2019 My Year.mp3", name: "2019 My Year" },
  { src: "songs/4 Instance.mp3", name: "4 Instance" },
  { src: "songs/6.mp3", name: "6" },
  { src: "songs/24 Hours.mp3", name: "24 Hours" },
  { src: "songs/27 Club.mp3", name: "27 Club" },
  { src: "songs/38 Special.mp3", name: "38 Special" },
  { src: "songs/70s.mp3", name: "'70s" },
  { src: "songs/Adore You.mp3", name: "Adore You" },
  {
    src: "songs/Airport Security.mp3",
    name: "Airport Security (feat. Lil Yachty)",
  },
  { src: "songs/All Out.mp3", name: "All Out" },
  { src: "songs/Anxiety.mp3", name: "Anxiety" },
  { src: "songs/Back In Chicago.mp3", name: "Back In Chicago" },
  { src: "songs/Barbarian (Vandal).mp3", name: "Barbarian (Vandal)" },
  { src: "songs/Best Of 'Em (Western).mp3", name: "Best Of 'Em (Western)" },
  { src: "songs/Big Dog.mp3", name: "Big Dog" },
  { src: "songs/Billy Idol (Mary Jane).mp3", name: "Billy Idol (Mary Jane)" },
  { src: "songs/Biscotti In The Air.mp3", name: "Biscotti In The Air" },
  { src: "songs/Both Ways.mp3", name: "Both Ways" },
  { src: "songs/Bottle.mp3", name: "Bottle" },
  { src: "songs/Bullet For My Valentine.mp3", name: "Bullet For My Valentine" },
  { src: "songs/Busch.mp3", name: "Busch" },
  { src: "songs/Cake.mp3", name: "Cake" },
  { src: "songs/Californication.mp3", name: "Californication" },
  { src: "songs/Chimp.mp3", name: "Chimp" },
  { src: "songs/Codeine Cobain.mp3", name: "Codeine Cobain" },
  { src: "songs/Common Sense (Worth It).mp3", name: "Common Sense (Worth It)" },
  { src: "songs/Condone It.mp3", name: "Condone It" },
  { src: "songs/Contained (Change).mp3", name: "Contained (Change)" },
  { src: "songs/Coraline.mp3", name: "Coraline" },
  { src: "songs/Cursed.mp3", name: "Cursed" },
  {
    src: "songs/Dark Thoughts (On Your Mind).mp3",
    name: "Dark Thoughts (On Your Mind)",
  },
  { src: "songs/Day One (v2).mp3", name: "Day One (v2)" },
  {
    src: "songs/Death Penalty (Dark Queen).mp3",
    name: "Death Penalty (Dark Queen)",
  },
  { src: "songs/Deprived.mp3", name: "Deprived" },
  {
    src: "songs/Do The Most (No Coaster).mp3",
    name: "Do The Most (No Coaster)",
  },
  { src: "songs/Don't Forget Me.mp3", name: "Don't Forget Me" },
  { src: "songs/Draco On Me.mp3", name: "Draco On Me" },
  { src: "songs/Drugs Are My Friends.mp3", name: "Drugs Are My Friends" },
  { src: "songs/Dummy.mp3", name: "Dummy" },
  { src: "songs/Fast Forward (Passport).mp3", name: "Fast Forward (Passport)" },
  { src: "songs/Fenty (Let It Go).mp3", name: "Fenty (Let It Go)" },
  { src: "songs/Flight To London.mp3", name: "Flight To London" },
  { src: "songs/Floor It.mp3", name: "Floor It" },
  {
    src: "songs/For The Team (feat. Lil Yachty).mp3",
    name: "For The Team (feat. Lil Yachty)",
  },
  { src: "songs/Four Words.mp3", name: "Four Words" },
  { src: "songs/Friends Die.mp3", name: "Friends Die" },
  { src: "songs/From Afar.mp3", name: "From Afar" },
  {
    src: "songs/Girl With The Blonde Hair.mp3",
    name: "Girl With The Blonde Hair",
  },
  { src: "songs/Give Me My Fix.mp3", name: "Give Me My Fix" },
  {
    src: "songs/Good Times (feat. Kid Cudi).mp3",
    name: "Good Times (feat. Kid Cudi)",
  },
  { src: "songs/GoPro.mp3", name: "GoPro" },
  { src: "songs/Goyard Bag.mp3", name: "Goyard Bag" },
  { src: "songs/Grace.mp3", name: "Grace" },
  { src: "songs/GTA.mp3", name: "GTA" },
  { src: "songs/Gucci Purse.mp3", name: "Gucci Purse" },
  { src: "songs/Hypnotic.mp3", name: "Hypnotic" },
  { src: "songs/I Want It (v1).mp3", name: "I Want It (v1)" },
  { src: "songs/I Wonder (My Mind).mp3", name: "I Wonder (My Mind)" },
  { src: "songs/In The Air.mp3", name: "In The Air" },
  {
    src: "songs/Inner Peace (Travelling).mp3",
    name: "Inner Peace (Travelling)",
  },
  { src: "songs/Irony (Inspire Me).mp3", name: "Irony (Inspire Me)" },
  { src: "songs/Irony.mp3", name: "Irony" },
  { src: "songs/Jeffery.mp3", name: "Jeffery" },
  { src: "songs/Karate Kid.mp3", name: "Karate Kid" },
  { src: "songs/Keep It.mp3", name: "Keep It" },
  { src: "songs/Kickflip.mp3", name: "Kickflip" },
  { src: "songs/KTM Drip.mp3", name: "KTM Drip" },
  { src: "songs/Let Me Be (Lone Ranger).mp3", name: "Let Me Be (Lone Ranger)" },
  { src: "songs/Life's A Dungeon.mp3", name: "Life's A Dungeon" },
  { src: "songs/Lock On (Dark Arts).mp3", name: "Lock On (Dark Arts)" },
  { src: "songs/Lonely.mp3", name: "Lonely" },
  { src: "songs/Long Time Coming.mp3", name: "Long Time Coming" },
  { src: "songs/Love Cage.mp3", name: "Love Cage" },
  { src: "songs/Love Over There.mp3", name: "Love Over There" },
  { src: "songs/Love Story.mp3", name: "Love Story" },
  { src: "songs/Luigi (Twins).mp3", name: "Luigi (Twins)" },
  { src: "songs/Made It Work.mp3", name: "Made It Work" },
  { src: "songs/Man Down (Rockstar Boy).mp3", name: "Man Down (Rockstar Boy)" },
  { src: "songs/Mansion.mp3", name: "Mansion" },
  { src: "songs/Maybe (Master).mp3", name: "Maybe (Master)" },
  {
    src: "songs/McLaren Drive (Tic-Tac-Toe).mp3",
    name: "McLaren Drive (Tic-Tac-Toe)",
  },
  { src: "songs/Meadows (Mix).mp3", name: "Meadows (Mix)" },
  { src: "songs/Minus.mp3", name: "Minus" },
  { src: "songs/Money Over Hoes.mp3", name: "Money Over Hoes" },
  { src: "songs/Morphine.mp3", name: "Morphine" },
  { src: "songs/My Year.mp3", name: "My Year" },
  { src: "songs/Naruto.mp3", name: "Naruto" },
  { src: "songs/Nesquick.mp3", name: "Nesquick" },
  { src: "songs/No Depot (Nemo).mp3", name: "No Depot (Nemo)" },
  { src: "songs/No Reason.mp3", name: "No Reason" },
  { src: "songs/No Wrong.mp3", name: "No Wrong" },
  {
    src: "songs/Nobody (feat. Lil Yachty).mp3",
    name: "Nobody (feat. Lil Yachty)",
  },
  { src: "songs/Not Sorry.mp3", name: "Not Sorry" },
  { src: "songs/Numb The Pain.mp3", name: "Numb The Pain" },
  { src: "songs/OJ Glove.mp3", name: "OJ Glove" },
  { src: "songs/Omen.mp3", name: "Omen" },
  { src: "songs/On The Regular.mp3", name: "On The Regular" },
  { src: "songs/On The Road.mp3", name: "On The Road" },
  { src: "songs/Only You On My Mind.mp3", name: "Only You On My Mind" },
  { src: "songs/Percaholic.mp3", name: "Percaholic" },
  { src: "songs/Potions.mp3", name: "Potions" },
  { src: "songs/Purple Moncler.mp3", name: "Purple Moncler" },
  { src: "songs/Quitter.mp3", name: "Quitter" },
  { src: "songs/Racks In.mp3", name: "Racks In" },
  { src: "songs/Rain Dance.mp3", name: "Rain Dance" },
  { src: "songs/Reason.mp3", name: "Reason" },
  { src: "songs/Red Dead Redemption.mp3", name: "Red Dead Redemption" },
  { src: "songs/Red Moonlight.mp3", name: "Red Moonlight" },
  { src: "songs/Remind Me Of The Summer.mp3", name: "Remind Me Of The Summer" },
  { src: "songs/Rental (Cha-Ching).mp3", name: "Rental (Cha-Ching)" },
  { src: "songs/Same Clothes.mp3", name: "Same Clothes" },
  { src: "songs/Sexual Healing.mp3", name: "Sexual Healing" },
  { src: "songs/Shadows.mp3", name: "Shadows" },
  { src: "songs/Singalong.mp3", name: "Singalong" },
  { src: "songs/Sippin Red.mp3", name: "Sippin Red" },
  { src: "songs/Sky High.mp3", name: "Sky High" },
  { src: "songs/Slasher.mp3", name: "Slasher" },
  { src: "songs/Sleep Paralysis.mp3", name: "Sleep Paralysis" },
  { src: "songs/Slow Me Down.mp3", name: "Slow Me Down" },
  { src: "songs/So Fast.mp3", name: "So Fast" },
  {
    src: "songs/Soda Pop (feat. Roddy Ricch).mp3",
    name: "Soda Pop (feat. Roddy Ricch)",
  },
  { src: "songs/Spanglish.mp3", name: "Spanglish" },
  {
    src: "songs/Split My Brain (808 Freestyle).mp3",
    name: "Split My Brain (808 Freestyle)",
  },
  { src: "songs/Stabbed You (Had To).mp3", name: "Stabbed You (Had To)" },
  {
    src: "songs/Stargazing (Not An Option).mp3",
    name: "Stargazing (Not An Option)",
  },
  { src: "songs/Starstruck (v3).mp3", name: "Starstruck (v3)" },
  { src: "songs/Stick Talk (Lavagirl).mp3", name: "Stick Talk (Lavagirl)" },
  { src: "songs/Stranger.mp3", name: "Stranger" },
  { src: "songs/Tales Of The Toxic.mp3", name: "Tales Of The Toxic" },
  { src: "songs/Talk Too Much(Master).mp3", name: "Talk Too Much" },
  { src: "songs/Through My Head.mp3", name: "Through My Head" },
  { src: "songs/To The Grave (Feelings).mp3", name: "To The Grave (Feelings)" },
  { src: "songs/Triple 9 (999).mp3", name: "Triple 9 (999)" },
  { src: "songs/Try Me.mp3", name: "Try Me" },
  { src: "songs/Under Her Skin.mp3", name: "Under Her Skin" },
  {
    src: "songs/Unexplainable.mp3",
    name: "Unexplainable (feat. The Kid LAROI)",
  },
  { src: "songs/Victorious.mp3", name: "Victorious" },
  { src: "songs/What Else.mp3", name: "What Else" },
  { src: "songs/Whip (Alaska).mp3", name: "Whip (Alaska)" },
  { src: "songs/Withdrawals.mp3", name: "Withdrawals (High Again)" },
  { src: "songs/X-Mas List.mp3", name: "X-Mas List" },
  { src: "songs/Z Nation.mp3", name: "Z Nation" },

  { src: "songs/All Alone (On My Own).mp3", name: "All Alone (On My Own)" },
  { src: "songs/Alright.mp3", name: "Alright" },
  {
    src: "songs/Always Workin' (Daily) (v2).mp3",
    name: "Alwas Workin' (Daily) (v2)",
  },
  { src: "songs/Analog.mp3", name: "Analog" },
  { src: "songs/Animal (v2).mp3", name: "Animal (v2)" },
  { src: "songs/Attachments.mp3", name: "Attachments" },
  { src: "songs/Bad Day.mp3", name: "Bad Day" },
  { src: "songs/Bentley Truck.mp3", name: "Bentley Truck" },
  { src: "songs/Beretta.mp3", name: "Beretta" },
  {
    src: "songs/Best Around (Racks Out).mp3",
    name: "Best Around (Racks Out)",
  },
  { src: "songs/Big Swag (v2).mp3", name: "Big Swag (v2)" },
  { src: "songs/Bitch You're Done (v2).mp3", name: "Bitch You're Done (v2)" },
  {
    src: "songs/Bitty (feat. Trippie Redd).mp3",
    name: "Bitty (feat. Trippie Redd)",
  },
  { src: "songs/Bonjour (On Tour).mp3", name: "Bonjour (On Tour)" },
  { src: "songs/Boondocks.mp3", name: "Boondocks" },
  { src: "songs/Boss Of Me.mp3", name: "Boss Of Me" },
  { src: "songs/Boy Wit Da Bandz.mp3", name: "Boy Wit Da Bandz" },
  { src: "songs/Bussin.mp3", name: "Bussin" },
  {
    src: "songs/Bye Bye Baby (feat. Young Thug).mp3",
    name: "Bye Bye Baby (feat. Young Thug)",
  },
  { src: "songs/Carry It.mp3", name: "Carry It" },
  { src: "songs/Chrome.mp3", name: "Chrome" },
  { src: "songs/Codeine Casket.mp3", name: "Codeine Casket" },
  { src: "songs/Come Around.mp3", name: "Come Around" },
  { src: "songs/Cursed Heart.mp3", name: "Cursed Heart" },
  { src: "songs/Dome.mp3", name: "Dome" },
  { src: "songs/Don't Go + Widow.mp3", name: "Don't Go + Widow" },
  { src: "songs/Dont Touch My Raf.mp3", name: "Dont Touch My Raf" },
  {
    src: "songs/Door (feat. Chance The Rapper & Ant Clemons).mp3",
    name: "Door (feat. Chance The Rapper)",
  },
  { src: "songs/Ducks.mp3", name: "Ducks" },
  { src: "songs/Everlasting Love.mp3", name: "Everlasting Love" },
  { src: "songs/Eyes Closed.mp3", name: "Eyes Closed" },
  { src: "songs/Eyes Up.mp3", name: "Eyes Up" },
  { src: "songs/Fire In My Lungs.mp3", name: "Fire In My Lungs" },
  { src: "songs/Flaws.mp3", name: "Flaws" },
  {
    src: "songs/Foo Foo (feat. G Herbo).mp3",
    name: "Foo Foo (feat. G Herbo)",
  },
  { src: "songs/Forever Love.mp3", name: "Forever Love" },
  { src: "songs/Fuck You Mean.mp3", name: "Fuck You Mean" },
  { src: "songs/Get Geeked.mp3", name: "Get Geeked" },
  { src: "songs/Girlfriend.mp3", name: "Girlfriend" },
  { src: "songs/Glock Handler.mp3", name: "Glock Handler" },
  { src: "songs/Good Day.mp3", name: "Good Day" },
  { src: "songs/Haha.mp3", name: "Haha" },
  { src: "songs/Hard To Digest.mp3", name: "Hard To Digest" },
  { src: "songs/Heroine Music.mp3", name: "Heroine Music" },
  { src: "songs/Hit A Lick.mp3", name: "Hit A Lick" },
  { src: "songs/Home.mp3", name: "Home" },
  { src: "songs/Hunnid.mp3", name: "Hunnid" },
  { src: "songs/I Wonder.mp3", name: "I Wonder" },
  { src: "songs/Iron On Me.mp3", name: "Iron On Me" },
  { src: "songs/Jack & Jill.mp3", name: "Jack & Jill" },
  { src: "songs/Juicy.mp3", name: "Juicy" },
  { src: "songs/Junkie.mp3", name: "Junkie" },
  { src: "songs/Kiki (King Kong).mp3", name: "Kiki (King Kong)" },
  { src: "songs/Kirby's Selecta.mp3", name: "Kirby's Selecta" },
  { src: "songs/Kurtis Blow.mp3", name: "Kurtis Blow" },
  { src: "songs/Late Night Thoughts.mp3", name: "Late Night Thoughts" },
  { src: "songs/Lavish.mp3", name: "Lavish" },
  { src: "songs/Lean Wit Me (v2).mp3", name: "Lean Wit Me (v2)" },
  { src: "songs/Left 4 Dead.mp3", name: "Left 4 Dead" },
  { src: "songs/Let's Go.mp3", name: "Let's Go" },
  { src: "songs/Live Forever.mp3", name: "Live Forever" },
  {
    src: "songs/Living At The Top (Simple).mp3",
    name: "Living At The Top (Simple)",
  },
  { src: "songs/London Tipton.mp3", name: "London Tipton" },
  { src: "songs/Lost Too Many (Goblin).mp3", name: "Lost Too Many (Goblin)" },
  { src: "songs/Love No Hoe.mp3", name: "Love No Hoe" },
  { src: "songs/Lullabies.mp3", name: "Lullabies" },
  { src: "songs/Lurkin (Sessions).mp3", name: "Lurkin (Sessions)" },
  { src: "songs/Make It Sell.mp3", name: "Make It Sell" },
  { src: "songs/Maserati.mp3", name: "Maserati" },
  { src: "songs/Meadows.mp3", name: "Meadows" },
  { src: "songs/Mind Games.mp3", name: "Mind Games" },
  { src: "songs/Misery Avenue (v3).mp3", name: "Misery Avenue (v3)" },
  { src: "songs/Molly & Mike.mp3", name: "Molly & Mike" },
  { src: "songs/Moncler Year.mp3", name: "Moncler Year" },
  { src: "songs/Mr. Heartbreak (v3).mp3", name: "Mr. Heartbreak (v3)" },
  { src: "songs/My Gang (Together).mp3", name: "My Gang (Together)" },
  { src: "songs/My Phone (Sessions).mp3", name: "My Phone (Sessions)" },
  { src: "songs/Narcotics.mp3", name: "Narcotics" },
  {
    src: "songs/Nascar (feat. 147 Calboy).mp3",
    name: "Nascar (feat. 147 Calboy)",
  },
  { src: "songs/Never Cared.mp3", name: "Never Cared" },
  { src: "songs/No Benefits.mp3", name: "No Benefits" },
  { src: "songs/No Fears.mp3", name: "No Fears" },
  { src: "songs/No Laces.mp3", name: "No Laces" },
  { src: "songs/No More.mp3", name: "No More" },
  { src: "songs/No Trespassing.mp3", name: "No Trespassing" },
  { src: "songs/Nobody (Blue Shit).mp3", name: "Nobody (Blue Shit)" },
  { src: "songs/Not Ashamed.mp3", name: "Not Ashamed" },
  { src: "songs/On Time.mp3", name: "On Time" },
  { src: "songs/Orange.mp3", name: "Orange" },
  { src: "songs/Oversprung.mp3", name: "Oversprung" },
  { src: "songs/Pain Feels.mp3", name: "Pain Feels" },
  { src: "songs/Pause.mp3", name: "Pause" },
  { src: "songs/Perc Floating.mp3", name: "Perc Floating" },
  { src: "songs/Plug.mp3", name: "Plug" },
  { src: "songs/Pop Rock.mp3", name: "Pop Rock" },
  {
    src: "songs/Psychedelic (Feeling Myself).mp3",
    name: "Psychedelic (Feeling Myself)",
  },
  { src: "songs/Purple Substance.mp3", name: "Purple Substance" },
  { src: "songs/Python.mp3", name: "Python" },
  { src: "songs/Rich Forever.mp3", name: "Rich Forever" },
  { src: "songs/Right Or Wrong.mp3", name: "Right Or Wrong" },
  { src: "songs/Rugrats.mp3", name: "Rugrats" },
  { src: "songs/Run That Shit.mp3", name: "Run That Shit" },
  { src: "songs/Scars.mp3", name: "Scars" },
  { src: "songs/Show Me Love (27 Club).mp3", name: "Show Me Love (27 Club)" },
  { src: "songs/Slenderman.mp3", name: "Slenderman" },
  { src: "songs/Slide.mp3", name: "Slide" },
  { src: "songs/So What.mp3", name: "So What" },
  {
    src: "songs/Stumblin' (feat. Lil Yachty).mp3",
    name: "Stumblin' (feat. Lil Yachty)",
  },
  { src: "songs/Sugarfish.mp3", name: "Sugarfish" },
  { src: "songs/Swear.mp3", name: "Swear" },
  { src: "songs/Swisher (Hilfiger).mp3", name: "Swisher (Hilfiger)" },
  { src: "songs/Tag.mp3", name: "Tag" },
  { src: "songs/Take Off (Sessions).mp3", name: "Take Off (Sessions)" },
  {
    src: "songs/Takeover (feat. Lil Yachty).mp3",
    name: "Takever (feat. Lil Yachty)",
  },
  { src: "songs/Tattoos And Ink.mp3", name: "Tattoos And Ink" },
  { src: "songs/Thrills.mp3", name: "Thrills" },
  { src: "songs/Tonight (feat. Valee).mp3", name: "Tonight (feat. Valee)" },
  {
    src: "songs/Trap Phone (feat. G Herbo).mp3",
    name: "Trap Phone (feat. G Herbo)",
  },
  { src: "songs/Trees.mp3", name: "Trees" },
  { src: "songs/Trick Or Treat.mp3", name: "Trick Or Treat" },
  { src: "songs/Used And Abused.mp3", name: "Used And Abused" },
  { src: "songs/VLone Thugs.mp3", name: "VLone Thugs" },
  { src: "songs/Waves.mp3", name: "Waves" },
  { src: "songs/Wavy.mp3", name: "Wavy" },
  {
    src: "songs/Morning Again (Remaster).mp3",
    name: "Morning Again (Remaster)",
  },
  {
    src: "songs/Toxic Humans (Remaster).mp3",
    name: "Toxic Humans (Remaster)",
  },
  { src: "songs/Aquafina.mp3", name: "Aquafina (Remaster)" },
  {
    src: "songs/Drive Me Crazy (Remaster).mp3",
    name: "Drive Me Crazy (Remaster)",
  },
];

// Export the songs array for use in other scripts
export default songlist;
